<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.4 Model Selection | STAT 155 Notes</title>
  <meta name="description" content="This includes notes for Introduction to Statistical Modeling (STAT 155) at Macalester College." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="7.4 Model Selection | STAT 155 Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This includes notes for Introduction to Statistical Modeling (STAT 155) at Macalester College." />
  <meta name="github-repo" content="bcheggeseth/Stat155Notes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.4 Model Selection | STAT 155 Notes" />
  
  <meta name="twitter:description" content="This includes notes for Introduction to Statistical Modeling (STAT 155) at Macalester College." />
  

<meta name="author" content="Macalester Statistics Faculty (Heggeseth, Myint, Grinde)" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hypothesis-testing.html"/>
<link rel="next" href="appendix-a---theoretical-probability.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">STAT 155 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="data-collection-and-quality.html"><a href="data-collection-and-quality.html"><i class="fa fa-check"></i><b>1</b> Data Collection and Quality</a>
<ul>
<li class="chapter" data-level="1.1" data-path="what-is-data.html"><a href="what-is-data.html"><i class="fa fa-check"></i><b>1.1</b> What is Data?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="what-is-data.html"><a href="what-is-data.html#tidy-data"><i class="fa fa-check"></i><b>1.1.1</b> Tidy Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="what-is-data.html"><a href="what-is-data.html#types-of-variables"><i class="fa fa-check"></i><b>1.1.2</b> Types of Variables</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="data-context.html"><a href="data-context.html"><i class="fa fa-check"></i><b>1.2</b> Data Context</a></li>
<li class="chapter" data-level="1.3" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>1.3</b> Sampling</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sampling.html"><a href="sampling.html#sampling-bias"><i class="fa fa-check"></i><b>1.3.1</b> Sampling Bias</a></li>
<li class="chapter" data-level="1.3.2" data-path="sampling.html"><a href="sampling.html#random-sampling"><i class="fa fa-check"></i><b>1.3.2</b> Random Sampling</a></li>
<li class="chapter" data-level="1.3.3" data-path="sampling.html"><a href="sampling.html#nonresponse-bias"><i class="fa fa-check"></i><b>1.3.3</b> Nonresponse bias</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="information-bias.html"><a href="information-bias.html"><i class="fa fa-check"></i><b>1.4</b> Information bias</a></li>
<li class="chapter" data-level="1.5" data-path="study-design.html"><a href="study-design.html"><i class="fa fa-check"></i><b>1.5</b> Study Design</a></li>
<li class="chapter" data-level="1.6" data-path="cause-and-effect.html"><a href="cause-and-effect.html"><i class="fa fa-check"></i><b>1.6</b> Cause and Effect</a></li>
<li class="chapter" data-level="1.7" data-path="ethical-considerations.html"><a href="ethical-considerations.html"><i class="fa fa-check"></i><b>1.7</b> Ethical Considerations</a></li>
<li class="chapter" data-level="1.8" data-path="chapter-1-major-takeaways.html"><a href="chapter-1-major-takeaways.html"><i class="fa fa-check"></i><b>1.8</b> Chapter 1 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data.html"><a href="visualizing-data.html"><i class="fa fa-check"></i><b>2</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="good-visualization-principles.html"><a href="good-visualization-principles.html"><i class="fa fa-check"></i><b>2.1</b> Good Visualization Principles</a></li>
<li class="chapter" data-level="2.2" data-path="brief-intro-to-r.html"><a href="brief-intro-to-r.html"><i class="fa fa-check"></i><b>2.2</b> Brief Intro to R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="brief-intro-to-r.html"><a href="brief-intro-to-r.html#basic-syntax"><i class="fa fa-check"></i><b>2.2.1</b> Basic Syntax</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="anatomy-of-a-ggplot-command.html"><a href="anatomy-of-a-ggplot-command.html"><i class="fa fa-check"></i><b>2.3</b> Anatomy of a ggplot command</a></li>
<li class="chapter" data-level="2.4" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html"><i class="fa fa-check"></i><b>2.4</b> One Categorical Variable</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html#bar-plot"><i class="fa fa-check"></i><b>2.4.1</b> Bar Plot</a></li>
<li class="chapter" data-level="2.4.2" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html#pie-chart"><i class="fa fa-check"></i><b>2.4.2</b> Pie Chart</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html"><i class="fa fa-check"></i><b>2.5</b> Two Categorical Variables</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#side-by-side-bar-plot"><i class="fa fa-check"></i><b>2.5.1</b> Side by Side Bar Plot</a></li>
<li class="chapter" data-level="2.5.2" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#stacked-bar-plot"><i class="fa fa-check"></i><b>2.5.2</b> Stacked Bar Plot</a></li>
<li class="chapter" data-level="2.5.3" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#stacked-bar-plot-relative-frequencies"><i class="fa fa-check"></i><b>2.5.3</b> Stacked Bar Plot (Relative Frequencies)</a></li>
<li class="chapter" data-level="2.5.4" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#mosaic-plot"><i class="fa fa-check"></i><b>2.5.4</b> Mosaic Plot</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html"><i class="fa fa-check"></i><b>2.6</b> One Quantitative Variable</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#histogram"><i class="fa fa-check"></i><b>2.6.1</b> Histogram</a></li>
<li class="chapter" data-level="2.6.2" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#center"><i class="fa fa-check"></i><b>2.6.2</b> Center</a></li>
<li class="chapter" data-level="2.6.3" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#boxplot"><i class="fa fa-check"></i><b>2.6.3</b> Boxplot</a></li>
<li class="chapter" data-level="2.6.4" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#spread"><i class="fa fa-check"></i><b>2.6.4</b> Spread</a></li>
<li class="chapter" data-level="2.6.5" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#intro-zscore"><i class="fa fa-check"></i><b>2.6.5</b> Some data accounting</a></li>
<li class="chapter" data-level="2.6.6" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#z-scores"><i class="fa fa-check"></i><b>2.6.6</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="one-quant.-and-one-cat.-variable.html"><a href="one-quant.-and-one-cat.-variable.html"><i class="fa fa-check"></i><b>2.7</b> One Quant. and One Cat. Variable</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="one-quant.-and-one-cat.-variable.html"><a href="one-quant.-and-one-cat.-variable.html#multiple-histograms"><i class="fa fa-check"></i><b>2.7.1</b> Multiple Histograms</a></li>
<li class="chapter" data-level="2.7.2" data-path="one-quant.-and-one-cat.-variable.html"><a href="one-quant.-and-one-cat.-variable.html#multiple-boxplots"><i class="fa fa-check"></i><b>2.7.2</b> Multiple Boxplots</a></li>
<li class="chapter" data-level="2.7.3" data-path="one-quant.-and-one-cat.-variable.html"><a href="one-quant.-and-one-cat.-variable.html#is-this-a-real-difference"><i class="fa fa-check"></i><b>2.7.3</b> Is this a Real Difference?</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html"><i class="fa fa-check"></i><b>2.8</b> Two Quantitative Variables</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#scatterplot"><i class="fa fa-check"></i><b>2.8.1</b> Scatterplot</a></li>
<li class="chapter" data-level="2.8.2" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#correlation-coefficient"><i class="fa fa-check"></i><b>2.8.2</b> Correlation Coefficient</a></li>
<li class="chapter" data-level="2.8.3" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#properties"><i class="fa fa-check"></i><b>2.8.3</b> Properties</a></li>
<li class="chapter" data-level="2.8.4" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#is-correlation-always-the-right-way-to-judge-strength"><i class="fa fa-check"></i><b>2.8.4</b> Is correlation always the right way to judge strength?</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html"><i class="fa fa-check"></i><b>2.9</b> Three or more variables</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#a-bivariate-scatterplot"><i class="fa fa-check"></i><b>2.9.1</b> A bivariate scatterplot</a></li>
<li class="chapter" data-level="2.9.2" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-color"><i class="fa fa-check"></i><b>2.9.2</b> Enriching with color</a></li>
<li class="chapter" data-level="2.9.3" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-shape"><i class="fa fa-check"></i><b>2.9.3</b> Enriching with shape</a></li>
<li class="chapter" data-level="2.9.4" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-size"><i class="fa fa-check"></i><b>2.9.4</b> Enriching with size</a></li>
<li class="chapter" data-level="2.9.5" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-panels"><i class="fa fa-check"></i><b>2.9.5</b> Enriching with panels</a></li>
<li class="chapter" data-level="2.9.6" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-smoothing"><i class="fa fa-check"></i><b>2.9.6</b> Enriching with smoothing</a></li>
<li class="chapter" data-level="2.9.7" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#putting-everything-together"><i class="fa fa-check"></i><b>2.9.7</b> Putting everything together</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="chapter-2-major-takeaways.html"><a href="chapter-2-major-takeaways.html"><i class="fa fa-check"></i><b>2.10</b> Chapter 2 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression-models.html"><a href="linear-regression-models.html"><i class="fa fa-check"></i><b>3</b> Linear Regression Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modeling-goals.html"><a href="modeling-goals.html"><i class="fa fa-check"></i><b>3.1</b> Modeling Goals</a></li>
<li class="chapter" data-level="3.2" data-path="lines.html"><a href="lines.html"><i class="fa fa-check"></i><b>3.2</b> Lines</a></li>
<li class="chapter" data-level="3.3" data-path="best-fitting-line.html"><a href="best-fitting-line.html"><i class="fa fa-check"></i><b>3.3</b> “Best” fitting line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="best-fitting-line.html"><a href="best-fitting-line.html#first-idea"><i class="fa fa-check"></i><b>3.3.1</b> First idea</a></li>
<li class="chapter" data-level="3.3.2" data-path="best-fitting-line.html"><a href="best-fitting-line.html#second-idea"><i class="fa fa-check"></i><b>3.3.2</b> Second idea</a></li>
<li class="chapter" data-level="3.3.3" data-path="best-fitting-line.html"><a href="best-fitting-line.html#third-idea"><i class="fa fa-check"></i><b>3.3.3</b> Third idea</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="least-squares.html"><a href="least-squares.html"><i class="fa fa-check"></i><b>3.4</b> Least Squares</a></li>
<li class="chapter" data-level="3.5" data-path="properties-of-least-squares-line.html"><a href="properties-of-least-squares-line.html"><i class="fa fa-check"></i><b>3.5</b> Properties of Least Squares Line</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="properties-of-least-squares-line.html"><a href="properties-of-least-squares-line.html#real-companies"><i class="fa fa-check"></i><b>3.5.1</b> Real companies</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="model-interpretation.html"><a href="model-interpretation.html"><i class="fa fa-check"></i><b>3.6</b> Model Interpretation</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="model-interpretation.html"><a href="model-interpretation.html#intercept-hatbeta_0"><i class="fa fa-check"></i><b>3.6.1</b> Intercept (<span class="math inline">\(\hat{\beta}_0\)</span>)</a></li>
<li class="chapter" data-level="3.6.2" data-path="model-interpretation.html"><a href="model-interpretation.html#slope-hatbeta_1"><i class="fa fa-check"></i><b>3.6.2</b> Slope (<span class="math inline">\(\hat{\beta}_1\)</span>)</a></li>
<li class="chapter" data-level="3.6.3" data-path="model-interpretation.html"><a href="model-interpretation.html#least-squares-regression-line-haty-hatbeta_0-hatbeta_1x"><i class="fa fa-check"></i><b>3.6.3</b> Least Squares Regression Line (<span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1x\)</span>)</a></li>
<li class="chapter" data-level="3.6.4" data-path="model-interpretation.html"><a href="model-interpretation.html#correlation-vs.-causation"><i class="fa fa-check"></i><b>3.6.4</b> Correlation vs. Causation</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="model-evaluation.html"><a href="model-evaluation.html"><i class="fa fa-check"></i><b>3.7</b> Model Evaluation</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="model-evaluation.html"><a href="model-evaluation.html#prediction"><i class="fa fa-check"></i><b>3.7.1</b> Prediction</a></li>
<li class="chapter" data-level="3.7.2" data-path="model-evaluation.html"><a href="model-evaluation.html#prediction-errors"><i class="fa fa-check"></i><b>3.7.2</b> Prediction Errors</a></li>
<li class="chapter" data-level="3.7.3" data-path="model-evaluation.html"><a href="model-evaluation.html#r2"><i class="fa fa-check"></i><b>3.7.3</b> <span class="math inline">\(R^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="conditions-for-linear-regression-models.html"><a href="conditions-for-linear-regression-models.html"><i class="fa fa-check"></i><b>3.8</b> Conditions for Linear Regression Models</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="conditions-for-linear-regression-models.html"><a href="conditions-for-linear-regression-models.html#residual-plot"><i class="fa fa-check"></i><b>3.8.1</b> Residual Plot</a></li>
<li class="chapter" data-level="3.8.2" data-path="conditions-for-linear-regression-models.html"><a href="conditions-for-linear-regression-models.html#sensitivity-analysis"><i class="fa fa-check"></i><b>3.8.2</b> Sensitivity Analysis</a></li>
<li class="chapter" data-level="3.8.3" data-path="conditions-for-linear-regression-models.html"><a href="conditions-for-linear-regression-models.html#issues-and-solutions"><i class="fa fa-check"></i><b>3.8.3</b> Issues and Solutions</a></li>
<li class="chapter" data-level="3.8.4" data-path="conditions-for-linear-regression-models.html"><a href="conditions-for-linear-regression-models.html#solutions-for-curvature"><i class="fa fa-check"></i><b>3.8.4</b> Solutions for Curvature</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="multiple.html"><a href="multiple.html"><i class="fa fa-check"></i><b>3.9</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="multiple.html"><a href="multiple.html#indicator-variables"><i class="fa fa-check"></i><b>3.9.1</b> Indicator Variables</a></li>
<li class="chapter" data-level="3.9.2" data-path="multiple.html"><a href="multiple.html#confounder-adjustment"><i class="fa fa-check"></i><b>3.9.2</b> Confounder Adjustment</a></li>
<li class="chapter" data-level="3.9.3" data-path="multiple.html"><a href="multiple.html#interaction-variables"><i class="fa fa-check"></i><b>3.9.3</b> Interaction Variables</a></li>
<li class="chapter" data-level="3.9.4" data-path="multiple.html"><a href="multiple.html#is-the-difference-real"><i class="fa fa-check"></i><b>3.9.4</b> Is the Difference Real?</a></li>
<li class="chapter" data-level="3.9.5" data-path="multiple.html"><a href="multiple.html#redundant"><i class="fa fa-check"></i><b>3.9.5</b> Redundancy and Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="selecting-a-model.html"><a href="selecting-a-model.html"><i class="fa fa-check"></i><b>3.10</b> Selecting a Model</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="selecting-a-model.html"><a href="selecting-a-model.html#satisfying-conditions"><i class="fa fa-check"></i><b>3.10.1</b> Satisfying conditions</a></li>
<li class="chapter" data-level="3.10.2" data-path="selecting-a-model.html"><a href="selecting-a-model.html#provide-useful-model"><i class="fa fa-check"></i><b>3.10.2</b> Provide useful model</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="dag.html"><a href="dag.html"><i class="fa fa-check"></i><b>3.11</b> Causal Inference</a></li>
<li class="chapter" data-level="3.12" data-path="chapter-3-major-takeaways.html"><a href="chapter-3-major-takeaways.html"><i class="fa fa-check"></i><b>3.12</b> Chapter 3 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="logistic.html"><a href="logistic.html"><i class="fa fa-check"></i><b>4</b> Logistic Regression Models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="logistic-and-logit.html"><a href="logistic-and-logit.html"><i class="fa fa-check"></i><b>4.1</b> Logistic and Logit</a></li>
<li class="chapter" data-level="4.2" data-path="fitting-the-model.html"><a href="fitting-the-model.html"><i class="fa fa-check"></i><b>4.2</b> Fitting the Model</a></li>
<li class="chapter" data-level="4.3" data-path="coefficient-interpretation.html"><a href="coefficient-interpretation.html"><i class="fa fa-check"></i><b>4.3</b> Coefficient Interpretation</a></li>
<li class="chapter" data-level="4.4" data-path="logistic-model-prediction.html"><a href="logistic-model-prediction.html"><i class="fa fa-check"></i><b>4.4</b> Logistic Model Prediction</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="logistic-model-prediction.html"><a href="logistic-model-prediction.html#hard-predictionsclassifications"><i class="fa fa-check"></i><b>4.4.1</b> Hard Predictions/Classifications</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="logistic-model-evaluation.html"><a href="logistic-model-evaluation.html"><i class="fa fa-check"></i><b>4.5</b> Logistic Model Evaluation</a></li>
<li class="chapter" data-level="4.6" data-path="alternative-classification-models.html"><a href="alternative-classification-models.html"><i class="fa fa-check"></i><b>4.6</b> Alternative Classification Models</a></li>
<li class="chapter" data-level="4.7" data-path="chapter-4-major-takeaways.html"><a href="chapter-4-major-takeaways.html"><i class="fa fa-check"></i><b>4.7</b> Chapter 4 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="randvariability.html"><a href="randvariability.html"><i class="fa fa-check"></i><b>5</b> Random Variability</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sampling-variability.html"><a href="sampling-variability.html"><i class="fa fa-check"></i><b>5.1</b> Sampling Variability</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sampling-variability.html"><a href="sampling-variability.html#simulating-random-sampling-from-a-population"><i class="fa fa-check"></i><b>5.1.1</b> Simulating Random Sampling from a Population</a></li>
<li class="chapter" data-level="5.1.2" data-path="sampling-variability.html"><a href="sampling-variability.html#irl-bootstrapping"><i class="fa fa-check"></i><b>5.1.2</b> IRL: Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomization-variability.html"><a href="randomization-variability.html"><i class="fa fa-check"></i><b>5.2</b> Randomization Variability</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="randomization-variability.html"><a href="randomization-variability.html#simulating-randomization-into-groups"><i class="fa fa-check"></i><b>5.2.1</b> Simulating Randomization into Groups</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomization-variability.html"><a href="randomization-variability.html#irl-randomization-tests"><i class="fa fa-check"></i><b>5.2.2</b> IRL: Randomization Tests</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chapter-5-major-takeaways.html"><a href="chapter-5-major-takeaways.html"><i class="fa fa-check"></i><b>5.3</b> Chapter 5 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html"><i class="fa fa-check"></i><b>6</b> Randomness and Probability</a>
<ul>
<li class="chapter" data-level="6.1" data-path="three-types-of-probability.html"><a href="three-types-of-probability.html"><i class="fa fa-check"></i><b>6.1</b> Three Types of Probability</a></li>
<li class="chapter" data-level="6.2" data-path="theoretical-probability-rules.html"><a href="theoretical-probability-rules.html"><i class="fa fa-check"></i><b>6.2</b> Theoretical Probability Rules</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="theoretical-probability-rules.html"><a href="theoretical-probability-rules.html#diagnotic-testing-and-probability"><i class="fa fa-check"></i><b>6.2.1</b> Diagnotic Testing and Probability</a></li>
<li class="chapter" data-level="6.2.2" data-path="theoretical-probability-rules.html"><a href="theoretical-probability-rules.html#court-arguments-and-probability"><i class="fa fa-check"></i><b>6.2.2</b> Court Arguments and Probability</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="random-variable.html"><a href="random-variable.html"><i class="fa fa-check"></i><b>6.3</b> Random Variable</a></li>
<li class="chapter" data-level="6.4" data-path="probability-models.html"><a href="probability-models.html"><i class="fa fa-check"></i><b>6.4</b> Probability Models</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="probability-models.html"><a href="probability-models.html#using-probability-mass-functions"><i class="fa fa-check"></i><b>6.4.1</b> Using probability mass functions</a></li>
<li class="chapter" data-level="6.4.2" data-path="probability-models.html"><a href="probability-models.html#using-probability-density-functions"><i class="fa fa-check"></i><b>6.4.2</b> Using probability density functions</a></li>
<li class="chapter" data-level="6.4.3" data-path="probability-models.html"><a href="probability-models.html#expected-value-and-variance"><i class="fa fa-check"></i><b>6.4.3</b> Expected value and variance</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="bernoullibinomial-model.html"><a href="bernoullibinomial-model.html"><i class="fa fa-check"></i><b>6.5</b> Bernoulli/Binomial Model</a></li>
<li class="chapter" data-level="6.6" data-path="normal-model.html"><a href="normal-model.html"><i class="fa fa-check"></i><b>6.6</b> Normal Model</a></li>
<li class="chapter" data-level="6.7" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html"><i class="fa fa-check"></i><b>6.7</b> Sampling Distribution and CLT</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html#sampling-distributions"><i class="fa fa-check"></i><b>6.7.1</b> Sampling distributions</a></li>
<li class="chapter" data-level="6.7.2" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.7.2</b> The Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html"><i class="fa fa-check"></i><b>6.8</b> Z-scores and the Student’s “t” distribution</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#gossets-work"><i class="fa fa-check"></i><b>6.8.1</b> Gosset’s Work</a></li>
<li class="chapter" data-level="6.8.2" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#beer-helps-the-field-of-statistics"><i class="fa fa-check"></i><b>6.8.2</b> Beer Helps the Field of Statistics</a></li>
<li class="chapter" data-level="6.8.3" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#students-t-model"><i class="fa fa-check"></i><b>6.8.3</b> Student’s T Model</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="regression-model-sampling-distributions.html"><a href="regression-model-sampling-distributions.html"><i class="fa fa-check"></i><b>6.9</b> Regression Model Sampling Distributions</a></li>
<li class="chapter" data-level="6.10" data-path="chapter-6-major-takeaways.html"><a href="chapter-6-major-takeaways.html"><i class="fa fa-check"></i><b>6.10</b> Chapter 6 Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>7</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="7.1" data-path="standard-error.html"><a href="standard-error.html"><i class="fa fa-check"></i><b>7.1</b> Standard Error</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="standard-error.html"><a href="standard-error.html#bootstrap-standard-error-estimate"><i class="fa fa-check"></i><b>7.1.1</b> Bootstrap Standard Error Estimate</a></li>
<li class="chapter" data-level="7.1.2" data-path="standard-error.html"><a href="standard-error.html#classical-standard-error-estimate"><i class="fa fa-check"></i><b>7.1.2</b> Classical Standard Error Estimate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7.2</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#properties-of-confidence-intervals"><i class="fa fa-check"></i><b>7.2.1</b> Properties of Confidence Intervals</a></li>
<li class="chapter" data-level="7.2.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#interval-construction-process"><i class="fa fa-check"></i><b>7.2.2</b> Interval Construction Process</a></li>
<li class="chapter" data-level="7.2.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-interpretation"><i class="fa fa-check"></i><b>7.2.3</b> Confidence Interval Interpretation</a></li>
<li class="chapter" data-level="7.2.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#more-examples"><i class="fa fa-check"></i><b>7.2.4</b> More Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>7.3</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-procedure"><i class="fa fa-check"></i><b>7.3.1</b> Hypothesis Test Procedure</a></li>
<li class="chapter" data-level="7.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-errors"><i class="fa fa-check"></i><b>7.3.2</b> Hypothesis Testing Errors</a></li>
<li class="chapter" data-level="7.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-significance-v.-practical-significance"><i class="fa fa-check"></i><b>7.3.3</b> Statistical Significance v. Practical Significance</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>7.4</b> Model Selection</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="model-selection.html"><a href="model-selection.html#testing-individual-slopes"><i class="fa fa-check"></i><b>7.4.1</b> Testing Individual Slopes</a></li>
<li class="chapter" data-level="7.4.2" data-path="model-selection.html"><a href="model-selection.html#nested-tests"><i class="fa fa-check"></i><b>7.4.2</b> Nested Tests</a></li>
<li class="chapter" data-level="7.4.3" data-path="model-selection.html"><a href="model-selection.html#summary-of-model-selection-methods"><i class="fa fa-check"></i><b>7.4.3</b> Summary of Model Selection Methods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="appendix-a---theoretical-probability.html"><a href="appendix-a---theoretical-probability.html"><i class="fa fa-check"></i><b>8</b> Appendix A - Theoretical Probability</a>
<ul>
<li class="chapter" data-level="8.1" data-path="probability-rules.html"><a href="probability-rules.html"><i class="fa fa-check"></i><b>8.1</b> Probability Rules</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="probability-rules.html"><a href="probability-rules.html#disjointmutually-exclusive"><i class="fa fa-check"></i><b>8.1.1</b> Disjoint/Mutually Exclusive</a></li>
<li class="chapter" data-level="8.1.2" data-path="probability-rules.html"><a href="probability-rules.html#independence"><i class="fa fa-check"></i><b>8.1.2</b> Independence</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="theory-of-random-variable.html"><a href="theory-of-random-variable.html"><i class="fa fa-check"></i><b>8.2</b> Theory of Random Variable</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="theory-of-random-variable.html"><a href="theory-of-random-variable.html#probability-models-1"><i class="fa fa-check"></i><b>8.2.1</b> Probability Models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html"><i class="fa fa-check"></i><b>8.3</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#expected-value"><i class="fa fa-check"></i><b>8.3.1</b> Expected Value</a></li>
<li class="chapter" data-level="8.3.2" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#variance"><i class="fa fa-check"></i><b>8.3.2</b> Variance</a></li>
<li class="chapter" data-level="8.3.3" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#joint-distributions"><i class="fa fa-check"></i><b>8.3.3</b> Joint Distributions</a></li>
<li class="chapter" data-level="8.3.4" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#covariance"><i class="fa fa-check"></i><b>8.3.4</b> Covariance</a></li>
<li class="chapter" data-level="8.3.5" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#correlation"><i class="fa fa-check"></i><b>8.3.5</b> Correlation</a></li>
<li class="chapter" data-level="8.3.6" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#a-few-named-probability-models"><i class="fa fa-check"></i><b>8.3.6</b> A Few Named Probability Models</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html"><i class="fa fa-check"></i><b>8.4</b> Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#expected-value-1"><i class="fa fa-check"></i><b>8.4.1</b> Expected Value</a></li>
<li class="chapter" data-level="8.4.2" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#a-few-named-probability-models-1"><i class="fa fa-check"></i><b>8.4.2</b> A Few Named Probability Models</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="random-variation.html"><a href="random-variation.html"><i class="fa fa-check"></i><b>8.5</b> Random Variation</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="definitions.html"><a href="definitions.html"><i class="fa fa-check"></i><b>9</b> Definitions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>9.1</b> Chapter 1</a></li>
<li class="chapter" data-level="9.2" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>9.2</b> Chapter 2</a></li>
<li class="chapter" data-level="9.3" data-path="chapter-3.html"><a href="chapter-3.html"><i class="fa fa-check"></i><b>9.3</b> Chapter 3</a></li>
<li class="chapter" data-level="9.4" data-path="chapter-4.html"><a href="chapter-4.html"><i class="fa fa-check"></i><b>9.4</b> Chapter 4</a></li>
<li class="chapter" data-level="9.5" data-path="chapter-5.html"><a href="chapter-5.html"><i class="fa fa-check"></i><b>9.5</b> Chapter 5</a></li>
<li class="chapter" data-level="9.6" data-path="chapter-6.html"><a href="chapter-6.html"><i class="fa fa-check"></i><b>9.6</b> Chapter 6</a></li>
<li class="chapter" data-level="9.7" data-path="chapter-7.html"><a href="chapter-7.html"><i class="fa fa-check"></i><b>9.7</b> Chapter 7</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 155 Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model-selection" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Model Selection</h2>
<p>For this class, we will use hypothesis testing primarily as a way to help us decide which variables should be included in an model. This is referred to as <strong>model selection</strong> or <strong>variable selection</strong>. We have many tools that can help us make these decisions. We’ll first discuss two types of hypothesis tests that are useful for model selection and explain another hypothesis test that is automatically completed when you fit a model. Finally, we summarize all of the model selection tools you have at your disposal that we’ve covered in this class and point to other tools that you may learn in future courses.</p>
<div id="testing-individual-slopes" class="section level3" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Testing Individual Slopes</h3>
<p>A major emphasis of our course is regression models. It turns out that many scientific questions of interest can be framed using regression models.</p>
<p>In the <code>tidy()</code> output, R performs the following hypothesis tests by default (for every slope coefficient <span class="math inline">\(\beta_j\)</span>):</p>
<p><span class="math display">\[H_0: \beta_j = 0 \qquad \text{vs} \qquad H_A: \beta_j \neq 0\]</span>
The test statistic is equal to the slope estimate divided by the standard error.</p>
<p><span class="math display">\[t_{obs} = \text{Test statistic} = \frac{\text{estimate} - \text{null value}}{\text{std. error of estimate}} = \frac{\text{estimate} - 0}{\text{std. error of estimate}} \]</span></p>
<p><strong>Linear Regression Example:</strong> Below we fit a linear regression model of house price on living area:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="model-selection.html#cb277-1" aria-hidden="true" tabindex="-1"></a>homes <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">&quot;http://sites.williams.edu/rdeveaux/files/2014/09/Saratoga.txt&quot;</span>)</span>
<span id="cb277-2"><a href="model-selection.html#cb277-2" aria-hidden="true" tabindex="-1"></a>mod_homes <span class="ot">&lt;-</span> homes <span class="sc">%&gt;%</span></span>
<span id="cb277-3"><a href="model-selection.html#cb277-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Living.Area))</span>
<span id="cb277-4"><a href="model-selection.html#cb277-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb277-5"><a href="model-selection.html#cb277-5" aria-hidden="true" tabindex="-1"></a>mod_homes <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic   p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)   13439.   4992.        2.69 7.17e-  3
## 2 Living.Area     113.      2.68     42.2  9.49e-268</code></pre>
<p>The <code>statistic</code> column is the test statistic equal to <code>estimate/std.error</code>, and the <code>p.value</code> column is the p-value.</p>
<ul>
<li><p>What are <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>?<br />
We write the model <span class="math inline">\(E[\text{Price}|\text{Living Area} ] = \beta_0 + \beta_1\text{Living Area}\)</span>.<br />
<span class="math inline">\(H_0: \beta_1 = 0\)</span> (There is no relationship between price and living area.)<br />
<span class="math inline">\(H_A: \beta_1 \neq 0\)</span> (There is a relationship between price and living area.)</p></li>
<li><p>What is the test statistic?
We see that the estimated slope for Living Area is 42 standard errors away from the null value of 0, which makes us start to doubt the null hypothesis of no relationship.</p></li>
<li><p>For a threshold <span class="math inline">\(\alpha = 0.05\)</span>, what is the decision regarding <span class="math inline">\(H_0\)</span>?<br />
Note that when you see <code>e</code> in R output, this means “10 to the power”. So <code>9.486240e-268</code> means <span class="math inline">\(9.49 \times 10^{-268}\)</span>, which is practically 0. This p-value is far less than our threshold <span class="math inline">\(\alpha = 0.05\)</span>, so we reject <span class="math inline">\(H_0\)</span> and say that we have strong evidence to support a relationship between price and living area.</p></li>
</ul>
<p>Is this consistent with conclusions from a confidence interval?</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="model-selection.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_homes)</span></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) 3647.6958 23231.0922
## Living.Area  107.8616   118.3835</code></pre>
<p>The interval does not include 0 so we conclude that 0 is not supported as a plausible value for the average increase in price for every 1 square foot increase in living area size of a house, based on the observed sample data.</p>
<p><strong>Logistic Regression Example:</strong> Below we fit a logistic regression model of whether a movie made a profit (response) on whether it is a history film:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="model-selection.html#cb281-1" aria-hidden="true" tabindex="-1"></a>movies <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://www.dropbox.com/s/73ad25v1epe0vpd/tmdb_movies.csv?dl=1&quot;</span>)</span>
<span id="cb281-2"><a href="model-selection.html#cb281-2" aria-hidden="true" tabindex="-1"></a>mod_movies <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb281-3"><a href="model-selection.html#cb281-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">glm</span>( profit <span class="sc">~</span> History, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>))</span>
<span id="cb281-4"><a href="model-selection.html#cb281-4" aria-hidden="true" tabindex="-1"></a>mod_movies <span class="sc">%&gt;%</span></span>
<span id="cb281-5"><a href="model-selection.html#cb281-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic     p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 (Intercept)   0.152     0.0296     5.15  0.000000258
## 2 HistoryTRUE   0.0207    0.146      0.142 0.887</code></pre>
<p>The <code>statistic</code> column is the test statistic equal to <code>estimate/std.error</code>, and the <code>p.value</code> column is the p-value. Note that if we test the slope, we can make conclusions about the odds ratios because <span class="math inline">\(e^0 = 1\)</span>.</p>
<p>Try yourself!</p>
<ul>
<li>What are <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>?</li>
<li>What is the test statistic?</li>
<li>For a threshold <span class="math inline">\(\alpha = 0.05\)</span>, what is the decision regarding <span class="math inline">\(H_0\)</span>?</li>
<li>Is this consistent with the confidence interval?</li>
</ul>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="model-selection.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_movies)</span></code></pre></div>
<pre><code>##                   2.5 %    97.5 %
## (Intercept)  0.09438169 0.2102419
## HistoryTRUE -0.26484980 0.3085225</code></pre>
<p>ANSWER:</p>
<ul>
<li><p>What are <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>?<br />
We write the model <span class="math inline">\(\log(Odds(\text{Profit}|\text{History})) = \beta_0 + \beta_1\text{HistoryTRUE}\)</span>.<br />
<span class="math inline">\(H_0: \beta_1 = 0\)</span> (There is no relationship between odds of profit and whether a movie is a history file.)<br />
<span class="math inline">\(H_A: \beta_1 \neq 0\)</span> (There is a relationship between odds of profit and whether a movie is a history file.)</p></li>
<li><p>What is the test statistic?
We see that the estimate slope for HistoryTRUE is 0.14 standard errors away from 0. This is not the far so we don’t have much evidence against the null hypothesis that history films are not more or less profitable than other films.</p></li>
<li><p>For a threshold <span class="math inline">\(\alpha = 0.05\)</span>, what is the decision regarding <span class="math inline">\(H_0\)</span>?<br />
The p-value is 0.88, which is quite large and greater than our threshold <span class="math inline">\(\alpha = 0.05\)</span>, so we fail to reject <span class="math inline">\(H_0\)</span> because it is quite likely to see an observed difference in estimated log odds of making a profit if history were not more or less likely to be profitable.</p></li>
<li><p>Is this consistent with the confidence interval?
Yes, the 95% confidence interval includes and in fact straddles 0, which suggests we are quite uncertain as to the true relationship between categorizing a film as a history film and the likelihood of it being profitable.</p></li>
</ul>
<div id="suggested-actions" class="section level4" number="7.4.1.1">
<h4><span class="header-section-number">7.4.1.1</span> Suggested Actions</h4>
<p>You might be wondering how to use the information gained by testing individual slopes to see if they are far from zero, taking into account the uncertainty in our estimates.</p>
<p>If the value of a slope coefficient in the population is truly 0, <em>after accounting for the other variables in the model</em>, then it plays no role in the model. If we get a small test statistic and thus a large p-value, it suggests that <em>we try to remove that slope</em> and corresponding variable from the model and compare models because we do not have enough evidence to say that the slope is far from 0, <em>after accounting for the other variables in the model</em>.</p>
<p>Notice, we say <em>try</em> to remove the variable. We do not say <em>eliminate</em> the variable from all models going forward because there are many reasons why a variable might have a slope of 0.</p>
<ul>
<li>A variable may not have any bearing or relationship with the outcome and thus the slope is practically 0. In these circumstances, you generally should remove it from the model because we want a simpler model with fewer variables.</li>
<li>A variable may have a weak relationship with the outcome, even <em>after accounting for the other variables in the model</em>, but if the sample size is small, there is so much uncertainty that we can’t ascertain that it is different from 0. You’ll need to decide whether or not it is important to include based on the context and causal inference arguments.</li>
<li>If two explanatory variables are highly correlated but can explain a lot of the variability in the outcome, they both have a slope near 0 because <em>after accounting for the other variable in the model</em>, it can’t add much. Try to remove one of the variables and see how the slope estimates change.</li>
<li>Two category levels in a categorical variable may not be that different (slope which measure the difference may be 0). You can try to combine categories that are similar, if it makes sense in the data context, or acknowledge the information gained about how those groups are not different, <em>after accounting for the other variable in the model</em>.</li>
</ul>
</div>
</div>
<div id="nested-tests" class="section level3" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Nested Tests</h3>
<p>If you’ve removed one or more variables from a model, the result is a smaller nested model. We can directly compare the larger model and the smaller <strong>nested model</strong> (from removing 1 or more variables from the larger model) using a hypothesis test.</p>
<p>For this test,</p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_0\)</span>): Smaller nested model is correct</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_A\)</span>): Smaller nested model is not correct and at least one of the removed variables has a non-zero slope in the population.</li>
</ul>
<p>In notation, we can write these hypotheses in terms of the larger model,</p>
<p><span class="math display">\[H_0: \beta_j = 0 \text{ for the variables removed} \qquad \text{vs} \qquad H_A: \beta_j \neq 0  \text{ for the variables removed}\]</span>
The test statistic for this nested test compares the smaller model to the larger full model; it is a measure of how much better the full model is over the smaller model. For a linear regression model, this test is called a <strong>nested F test</strong> and the test statistic is a ratio comparing the sum of squared residuals (F ~ 1 if <span class="math inline">\(H_0\)</span> is true). For logistic regression, this nested test is called a <strong>likelihood ratio test</strong> and the test statistic is a ratio comparing the likelihood or “goodness” of a model (Chi ~ 1 if <span class="math inline">\(H_0\)</span> is true). The larger the test statistics are, the bigger the difference is between the smaller model (<span class="math inline">\(H_0\)</span>) and the larger model, suggesting that the larger model might be better.</p>
<p>We can compare these models in R using the <code>anova()</code> function.</p>
<p><strong>Linear Regression Example:</strong> Below we fit a larger linear regression model of house price using living area, the number of bedrooms, and the number of bathrooms:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="model-selection.html#cb285-1" aria-hidden="true" tabindex="-1"></a>mod_homes_full <span class="ot">&lt;-</span> homes <span class="sc">%&gt;%</span></span>
<span id="cb285-2"><a href="model-selection.html#cb285-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Living.Area <span class="sc">+</span> Bedrooms <span class="sc">+</span> Bathrooms))</span>
<span id="cb285-3"><a href="model-selection.html#cb285-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb285-4"><a href="model-selection.html#cb285-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_homes,mod_homes_full)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Price ~ Living.Area
## Model 2: Price ~ Living.Area + Bedrooms + Bathrooms
##   Res.Df        RSS Df  Sum of Sq      F    Pr(&gt;F)    
## 1   1726 8.2424e+12                                   
## 2   1724 7.8671e+12  2 3.7534e+11 41.126 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notice that we get the smaller nested model by removing <code>Bedrooms</code> and <code>Bathrooms</code> from the larger model. This means that they are nested and can be compared using the nested test.</p>
<ul>
<li><p>What are <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>?
<span class="math inline">\(H_0\)</span>: The smaller model with just Living.Area is correct; the number of Bathrooms and Bedrooms do not have an impact on average price after accounting for living area.
<span class="math inline">\(H_A\)</span>: The smaller model with just Living.Area is not correct; the number of Bathrooms or Bedrooms do have an impact on average price after accounting for living area.</p></li>
<li><p>What is the test statistic?
The F = 41.126 is the test statistic. Unlike the test for slopes, this test statistic does not have a nice interpretation. It seems quite far from 1 (which is what F should be close to if <span class="math inline">\(H_0\)</span> were true), but there are no rules for “how far is far”.</p></li>
<li><p>For a threshold <span class="math inline">\(\alpha = 0.05\)</span>, what is the decision regarding <span class="math inline">\(H_0\)</span>?
The p-value of <span class="math inline">\(&lt; 2.2*10^{-16}\)</span> is well below the threshold suggesting that it is very unlikely to have observed a difference between these two models as big as we did if the smaller model were true. Thus, we reject <span class="math inline">\(H_0\)</span> that the model with only living area is correct in favor of the larger model.</p></li>
</ul>
<p><strong>Logistic Regression Example:</strong> Below we fit a larger logistic regression model of whether a movie made a profit (response) based on whether it is a history, drama, comedy, or a family film:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="model-selection.html#cb287-1" aria-hidden="true" tabindex="-1"></a>mod_movies_full <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb287-2"><a href="model-selection.html#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">glm</span>( profit <span class="sc">~</span> History <span class="sc">+</span> Drama <span class="sc">+</span> Comedy <span class="sc">+</span> Family, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>))</span>
<span id="cb287-3"><a href="model-selection.html#cb287-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb287-4"><a href="model-selection.html#cb287-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_movies,mod_movies_full,<span class="at">test=</span><span class="st">&#39;LRT&#39;</span>) <span class="co">#test=&#39;LRT&#39; is needed for logistic models</span></span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: profit ~ History
## Model 2: profit ~ History + Drama + Comedy + Family
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1      4801     6630.3                          
## 2      4798     6555.3  3   74.941 3.729e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notice that we get the smaller nested model by removing <code>Drama</code>, <code>Comedy</code>, and <code>Family</code> from the larger model. This means that they are nested and can be compared using the nested test.</p>
<ul>
<li><p>What are <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>?
<span class="math inline">\(H_0\)</span>: The smaller model with just History is correct; indicators of Drama, Comedy, and Family do not have an impact on whether a movie makes a profit.
<span class="math inline">\(H_A\)</span>: The smaller model with just History is not correct; indicators of Drama, Comedy, or Family do have an impact on whether a movie makes a profit.</p></li>
<li><p>What is the test statistic?
The Deviance = 74.941 is the test statistic. Unlike the test for slopes, this test statistic does not have a nice interpretation. It seems quite far from 1 (which is it should be close to if <span class="math inline">\(H_0\)</span> were true), but there are no rules for “how far is far”.</p></li>
<li><p>For a threshold <span class="math inline">\(\alpha = 0.05\)</span>, what is the decision regarding <span class="math inline">\(H_0\)</span>?
The p-value of <span class="math inline">\(3.729 * 10^{-16}\)</span> is well below the threshold suggesting that it is very unlikely to have observed a difference between these two models as big as we did if the smaller model were true. Thus, we reject <span class="math inline">\(H_0\)</span> that the model with only History indicator is correct in favor of the larger model.</p></li>
</ul>
<div id="suggested-actions-1" class="section level4" number="7.4.2.1">
<h4><span class="header-section-number">7.4.2.1</span> Suggested Actions</h4>
<p>You might be wondering how to use the information gained by comparing a smaller nested model to a larger model.</p>
<ul>
<li>If the p-value is large, then you don’t have evidence to support the larger model.</li>
<li>If the p-value is small, then you need to look back at the variables you removed.</li>
</ul>
<p>This tool is particularly helpful if you have a categorical variable with three or more categories as you can test all of the slopes for that one variable at once.</p>
<p>This tools can also be helpful to stop you from removing too many variables at once.</p>
<p>In practice, you can iterate between testing individual slopes to determine which variables to consider removing and then comparing nested models. Also, you’ll incorporate other model selection tools in your process, not just these two types of hypothesis tests.</p>
</div>
</div>
<div id="summary-of-model-selection-methods" class="section level3" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Summary of Model Selection Methods</h3>
<p>In general, we want a simple model that works well. We want to follow Occam’s Razor, a philosophy that suggests that it is a good principle to explain the phenomena by the simplest hypothesis possible. In our case, that mean the fewest variables in our models.</p>
<div id="linear-regression-tools" class="section level4" number="7.4.3.1">
<h4><span class="header-section-number">7.4.3.1</span> Linear Regression Tools</h4>
<ul>
<li>Exploratory visualizations give us an indication for which variables have the strongest relationship with our response of interest (also if it is not linear)</li>
<li><span class="math inline">\(R^2\)</span> can tell us the percent of variation in our response that is explained by the model – We want HIGH <span class="math inline">\(R^2\)</span></li>
<li>The standard deviation of the residuals, <span class="math inline">\(s_e\)</span> (residual standard error), tells us the average magnitude of our residuals (prediction errors for our data set) – We want LOW <span class="math inline">\(s_e\)</span></li>
</ul>
<p>With the addition of statistical inference in our tool set, we now have many other ways to help guide our decision making process.</p>
<ul>
<li>Confidence intervals or tests for individual coefficients or slopes (<span class="math inline">\(H_0: \beta_k = 0\)</span>, population slope for kth variable is 0 meaning no relationship)
<ul>
<li>See <code>tidy(lm1)</code></li>
</ul></li>
<li>Nested tests for a subset of coefficients or slopes (<span class="math inline">\(H_0: \beta_k = 0\)</span>, population slope for kth variable is 0 meaning no relationship)
<ul>
<li><code>anova(lm1, lm2)</code> for comparing two linear regression models (one larger model and one model with some variables removed)</li>
</ul></li>
</ul>
<p>So there are model selection criteria that we can use that penalizes you for having too many variables. Here are some below.</p>
<ul>
<li>Choose a model with a higher adjusted <span class="math inline">\(R^2\)</span>, calculated as,
<span class="math display">\[R^2_{adj} = 1 - \frac{SSE/(n-k-1)}{SSTO/(n-1)}\]</span>
where <span class="math inline">\(k\)</span> is the number of estimated coefficients in the model.
<ul>
<li>Find the adjusted R squared in the output of <code>glance(lm1)</code></li>
</ul></li>
</ul>
</div>
<div id="logistic-regression-tools" class="section level4" number="7.4.3.2">
<h4><span class="header-section-number">7.4.3.2</span> Logistic Regression Tools</h4>
<ul>
<li>Exploratory visualizations give us an indication for which variables have the strongest relationship with our response of interest (also if it is not linear)<br />
</li>
<li>We want HIGH accuracy and LOW false positive and false negative rates that can separate predicted probabilities fairly well between the true outcome groups.</li>
</ul>
<p>With the addition of statistical inference in our tool set, we now have many other ways to help guide our decision making process.</p>
<ul>
<li>Confidence intervals or tests for individual coefficients or slopes (<span class="math inline">\(H_0: \beta_k = 0\)</span>, population slope for kth variable is 0 meaning no relationship)
<ul>
<li>See <code>tidy(lm1)</code></li>
</ul></li>
<li>Nested tests for a subset of coefficients or slopes (<span class="math inline">\(H_0: \beta_k = 0\)</span>, population slope for kth variable is 0 meaning no relationship)
<ul>
<li><code>anova(glm1, glm2, test = 'LRT')</code> for comparing two logistic regression models (one larger model and one model with some variables removed)</li>
</ul></li>
</ul>
<p>So there are model selection criteria that we can use that penalizes you for having too many variables. Here are some below that you’ll see in future classes.</p>
<ul>
<li>Choose a model with a LOWER Akaike Information Criterion (AIC) and Bayesian Information Criterion (BIC) calculated as</li>
</ul>
<p><span class="math display">\[AIC = -2\log(L) + 2(k+1)\]</span>
<span class="math display">\[BIC= -2\log(L) + (k+1)\log(n)\]</span><br />
- Calculated using <code>BIC(glm1)</code> and <code>AIC(glm1)</code></p>
</div>
<div id="prediction-tools" class="section level4" number="7.4.3.3">
<h4><span class="header-section-number">7.4.3.3</span> Prediction Tools</h4>
<p>Here is a taste of Statistical Machine Learning:</p>
<p>If our goal is prediction, then we will want to choose a model that has the lowest prediction error. BUT, if we fit our model to our data and then calculate the prediction error from that SAME data, we aren’t getting an accurate estimate of the prediction error because we are cheating. We aren’t doing predictions for new data values.</p>
<p><strong>Training and Testing</strong></p>
<p>In order to be able to predict for new data, we can randomly split our observed data into two groups, a <strong>training</strong> set and a <strong>testing</strong> set (also known as a validation or hold-out set).</p>
<ul>
<li>Fit the model to the training set and do prediction on the observations in the testing set.</li>
<li>The prediction Mean Squared Error, <span class="math inline">\(\frac{1}{n}\sum(y_i - \hat{y}_i)^2\)</span> can be calulated based on the predictions from the testing set.</li>
</ul>
<p><strong>Drawbacks of Validation Testing</strong></p>
<ul>
<li><ol style="list-style-type: decimal">
<li>The MSE can be highly variable as it depends on how you randomly split the data.</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>We aren’t fully utilizing all of our data to fit the model; therefore, we will tend to overestimate the prediction error.</li>
</ol></li>
</ul>
<p><strong>K-Fold Cross-Validation</strong></p>
<p>If we have a small data set and we want to fully use all of the data in our training, we can do <strong>K-Fold Cross-Validation</strong>. The steps are as follows:</p>
<ul>
<li><p>Randomly splitting the set of observations into <span class="math inline">\(k\)</span> groups, or folds, of about equal size.</p></li>
<li><p>The first group is treated as the test set and the method or model is fit on the remaining <span class="math inline">\(k-1\)</span> groups. The MSE is calculated on the observations in the test set.</p></li>
<li><p>Repeat <span class="math inline">\(k\)</span> times; each group is treated as the test set once.</p></li>
<li><p>The k-fold CV estimate of MSE is an average of these values,
<span class="math display">\[CV_{(k)} = \frac{1}{k}\sum^k_{i=1}MSE_i \]</span>
where <span class="math inline">\(MSE_i\)</span> is the MSE based on the <span class="math inline">\(i\)</span>th group as the test group. In practice, one performs k-fold CV with <span class="math inline">\(k=5\)</span> or <span class="math inline">\(k=10\)</span> as it reduces the computational time and it also is more accurate.</p></li>
</ul>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="model-selection.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(boot)</span>
<span id="cb289-2"><a href="model-selection.html#cb289-2" aria-hidden="true" tabindex="-1"></a>cv.err <span class="ot">&lt;-</span> <span class="fu">cv.glm</span>(data,glm1, <span class="at">K =</span> <span class="dv">5</span>)</span>
<span id="cb289-3"><a href="model-selection.html#cb289-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(cv.err<span class="sc">$</span>delta[<span class="dv">1</span>]) <span class="co">#out of sample average prediction error</span></span></code></pre></div>
<p>##Chapter 7 Major Takeaways</p>

<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;mosaic&#39;:
##   method                           from   
##   fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
<pre><code>## 
## The &#39;mosaic&#39; package masks several functions from core packages in order to add 
## additional features.  The original behavior of these functions should not be affected by this.</code></pre>
<pre><code>## 
## Attaching package: &#39;mosaic&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Matrix&#39;:
## 
##     mean</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     stat</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     count, do, tally</code></pre>
<pre><code>## The following objects are masked from &#39;package:infer&#39;:
## 
##     prop_test, t_test</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
##     quantile, sd, t.test, var</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     max, mean, min, prod, range, sample, sum</code></pre>
</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="hypothesis-testing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-a---theoretical-probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07-inference.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Stat155Notes.pdf"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
