<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.9 Multiple Linear Regression | Stat 155 Notes</title>
  <meta name="description" content="This includes notes for STAT 155 at Macalester College." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="3.9 Multiple Linear Regression | Stat 155 Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This includes notes for STAT 155 at Macalester College." />
  <meta name="github-repo" content="bcheggeseth/Stat155Notes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.9 Multiple Linear Regression | Stat 155 Notes" />
  
  <meta name="twitter:description" content="This includes notes for STAT 155 at Macalester College." />
  

<meta name="author" content="Brianna Heggeseth &amp; Leslie Myint" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="diagnostics.html">
<link rel="next" href="logistic-regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"Stat 155 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="data-collection-and-quality.html"><a href="data-collection-and-quality.html"><i class="fa fa-check"></i><b>1</b> Data Collection and Quality</a><ul>
<li class="chapter" data-level="1.1" data-path="what-is-data.html"><a href="what-is-data.html"><i class="fa fa-check"></i><b>1.1</b> What is Data?</a></li>
<li class="chapter" data-level="1.2" data-path="data-context.html"><a href="data-context.html"><i class="fa fa-check"></i><b>1.2</b> Data Context</a></li>
<li class="chapter" data-level="1.3" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>1.3</b> Sampling</a><ul>
<li class="chapter" data-level="1.3.1" data-path="sampling.html"><a href="sampling.html#sampling-bias"><i class="fa fa-check"></i><b>1.3.1</b> Sampling Bias</a></li>
<li class="chapter" data-level="1.3.2" data-path="sampling.html"><a href="sampling.html#random-sampling"><i class="fa fa-check"></i><b>1.3.2</b> Random Sampling</a></li>
<li class="chapter" data-level="1.3.3" data-path="sampling.html"><a href="sampling.html#nonresponse-bias"><i class="fa fa-check"></i><b>1.3.3</b> Nonresponse bias</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="information-bias.html"><a href="information-bias.html"><i class="fa fa-check"></i><b>1.4</b> Information bias</a></li>
<li class="chapter" data-level="1.5" data-path="study-design-observational-study-vs-experiments.html"><a href="study-design-observational-study-vs-experiments.html"><i class="fa fa-check"></i><b>1.5</b> Study Design: Observational Study vs. Experiments</a></li>
<li class="chapter" data-level="1.6" data-path="ethical-considerations.html"><a href="ethical-considerations.html"><i class="fa fa-check"></i><b>1.6</b> Ethical Considerations</a></li>
<li class="chapter" data-level="1.7" data-path="major-takeaways.html"><a href="major-takeaways.html"><i class="fa fa-check"></i><b>1.7</b> Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data.html"><a href="visualizing-data.html"><i class="fa fa-check"></i><b>2</b> Visualizing Data</a><ul>
<li class="chapter" data-level="2.1" data-path="good-visualization-principles.html"><a href="good-visualization-principles.html"><i class="fa fa-check"></i><b>2.1</b> Good Visualization Principles</a></li>
<li class="chapter" data-level="2.2" data-path="anatomy-of-a-ggplot-command.html"><a href="anatomy-of-a-ggplot-command.html"><i class="fa fa-check"></i><b>2.2</b> Anatomy of a ggplot command</a></li>
<li class="chapter" data-level="2.3" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html"><i class="fa fa-check"></i><b>2.3</b> One Categorical Variable</a><ul>
<li class="chapter" data-level="2.3.1" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html#bar-plot"><i class="fa fa-check"></i><b>2.3.1</b> Bar Plot</a></li>
<li class="chapter" data-level="2.3.2" data-path="one-categorical-variable.html"><a href="one-categorical-variable.html#pie-chart"><i class="fa fa-check"></i><b>2.3.2</b> Pie Chart</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html"><i class="fa fa-check"></i><b>2.4</b> Two Categorical Variables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#side-by-side-bar-plot"><i class="fa fa-check"></i><b>2.4.1</b> Side by Side Bar Plot</a></li>
<li class="chapter" data-level="2.4.2" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#stacked-bar-plot"><i class="fa fa-check"></i><b>2.4.2</b> Stacked Bar Plot</a></li>
<li class="chapter" data-level="2.4.3" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#stacked-bar-plot-relative-frequencies"><i class="fa fa-check"></i><b>2.4.3</b> Stacked Bar Plot (Relative Frequencies)</a></li>
<li class="chapter" data-level="2.4.4" data-path="two-categorical-variables.html"><a href="two-categorical-variables.html#mosaic-plot"><i class="fa fa-check"></i><b>2.4.4</b> Mosaic Plot</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html"><i class="fa fa-check"></i><b>2.5</b> One Quantitative Variable</a><ul>
<li class="chapter" data-level="2.5.1" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#histogram"><i class="fa fa-check"></i><b>2.5.1</b> Histogram</a></li>
<li class="chapter" data-level="2.5.2" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#center"><i class="fa fa-check"></i><b>2.5.2</b> Center</a></li>
<li class="chapter" data-level="2.5.3" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#boxplot"><i class="fa fa-check"></i><b>2.5.3</b> Boxplot</a></li>
<li class="chapter" data-level="2.5.4" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#spread"><i class="fa fa-check"></i><b>2.5.4</b> Spread</a></li>
<li class="chapter" data-level="2.5.5" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#intro-zscore"><i class="fa fa-check"></i><b>2.5.5</b> Some data accounting</a></li>
<li class="chapter" data-level="2.5.6" data-path="one-quantitative-variable.html"><a href="one-quantitative-variable.html#z-scores"><i class="fa fa-check"></i><b>2.5.6</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="one-quantitative-variable-and-one-categorical-variable.html"><a href="one-quantitative-variable-and-one-categorical-variable.html"><i class="fa fa-check"></i><b>2.6</b> One Quantitative Variable and One Categorical Variable</a><ul>
<li class="chapter" data-level="2.6.1" data-path="one-quantitative-variable-and-one-categorical-variable.html"><a href="one-quantitative-variable-and-one-categorical-variable.html#multiple-histograms"><i class="fa fa-check"></i><b>2.6.1</b> Multiple Histograms</a></li>
<li class="chapter" data-level="2.6.2" data-path="one-quantitative-variable-and-one-categorical-variable.html"><a href="one-quantitative-variable-and-one-categorical-variable.html#multiple-boxplots"><i class="fa fa-check"></i><b>2.6.2</b> Multiple Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html"><i class="fa fa-check"></i><b>2.7</b> Two Quantitative Variables</a><ul>
<li class="chapter" data-level="2.7.1" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#scatterplot"><i class="fa fa-check"></i><b>2.7.1</b> Scatterplot</a></li>
<li class="chapter" data-level="2.7.2" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#correlation-coefficient"><i class="fa fa-check"></i><b>2.7.2</b> Correlation Coefficient</a></li>
<li class="chapter" data-level="2.7.3" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#properties"><i class="fa fa-check"></i><b>2.7.3</b> Properties</a></li>
<li class="chapter" data-level="2.7.4" data-path="two-quantitative-variables.html"><a href="two-quantitative-variables.html#is-correlation-always-the-right-way-to-judge-strength"><i class="fa fa-check"></i><b>2.7.4</b> Is correlation always the right way to judge strength?</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html"><i class="fa fa-check"></i><b>2.8</b> Three or more variables</a><ul>
<li class="chapter" data-level="2.8.1" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#a-bivariate-plot"><i class="fa fa-check"></i><b>2.8.1</b> A bivariate plot</a></li>
<li class="chapter" data-level="2.8.2" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-color"><i class="fa fa-check"></i><b>2.8.2</b> Enriching with color</a></li>
<li class="chapter" data-level="2.8.3" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-shape"><i class="fa fa-check"></i><b>2.8.3</b> Enriching with shape</a></li>
<li class="chapter" data-level="2.8.4" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-size"><i class="fa fa-check"></i><b>2.8.4</b> Enriching with size</a></li>
<li class="chapter" data-level="2.8.5" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#enriching-with-panels"><i class="fa fa-check"></i><b>2.8.5</b> Enriching with panels</a></li>
<li class="chapter" data-level="2.8.6" data-path="three-or-more-variables.html"><a href="three-or-more-variables.html#putting-everything-together"><i class="fa fa-check"></i><b>2.8.6</b> Putting everything together</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="major-takeaways-1.html"><a href="major-takeaways-1.html"><i class="fa fa-check"></i><b>2.9</b> Major Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-models.html"><a href="regression-models.html"><i class="fa fa-check"></i><b>3</b> Regression Models</a><ul>
<li class="chapter" data-level="3.1" data-path="goals-for-models.html"><a href="goals-for-models.html"><i class="fa fa-check"></i><b>3.1</b> Goals for models</a></li>
<li class="chapter" data-level="3.2" data-path="lines.html"><a href="lines.html"><i class="fa fa-check"></i><b>3.2</b> Lines</a></li>
<li class="chapter" data-level="3.3" data-path="choosing-the-best-fitting-line.html"><a href="choosing-the-best-fitting-line.html"><i class="fa fa-check"></i><b>3.3</b> Choosing the best fitting line</a><ul>
<li class="chapter" data-level="3.3.1" data-path="choosing-the-best-fitting-line.html"><a href="choosing-the-best-fitting-line.html#first-idea"><i class="fa fa-check"></i><b>3.3.1</b> First idea</a></li>
<li class="chapter" data-level="3.3.2" data-path="choosing-the-best-fitting-line.html"><a href="choosing-the-best-fitting-line.html#second-idea"><i class="fa fa-check"></i><b>3.3.2</b> Second idea</a></li>
<li class="chapter" data-level="3.3.3" data-path="choosing-the-best-fitting-line.html"><a href="choosing-the-best-fitting-line.html#third-idea"><i class="fa fa-check"></i><b>3.3.3</b> Third idea</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="least-squares.html"><a href="least-squares.html"><i class="fa fa-check"></i><b>3.4</b> Least Squares</a></li>
<li class="chapter" data-level="3.5" data-path="properties-of-least-squares-line.html"><a href="properties-of-least-squares-line.html"><i class="fa fa-check"></i><b>3.5</b> Properties of Least Squares Line</a><ul>
<li class="chapter" data-level="3.5.1" data-path="properties-of-least-squares-line.html"><a href="properties-of-least-squares-line.html#real-companies"><i class="fa fa-check"></i><b>3.5.1</b> Real companies</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="interpretation.html"><a href="interpretation.html"><i class="fa fa-check"></i><b>3.6</b> Interpretation</a><ul>
<li class="chapter" data-level="3.6.1" data-path="interpretation.html"><a href="interpretation.html#correlation-or-association-vs.causation"><i class="fa fa-check"></i><b>3.6.1</b> Correlation or Association vs. Causation</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="evaluation.html"><a href="evaluation.html"><i class="fa fa-check"></i><b>3.7</b> Evaluation</a><ul>
<li class="chapter" data-level="3.7.1" data-path="evaluation.html"><a href="evaluation.html#prediction"><i class="fa fa-check"></i><b>3.7.1</b> Prediction</a></li>
<li class="chapter" data-level="3.7.2" data-path="evaluation.html"><a href="evaluation.html#prediction-errors"><i class="fa fa-check"></i><b>3.7.2</b> Prediction Errors</a></li>
<li class="chapter" data-level="3.7.3" data-path="evaluation.html"><a href="evaluation.html#r2"><i class="fa fa-check"></i><b>3.7.3</b> <span class="math inline">\(R^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>3.8</b> Diagnostics</a><ul>
<li class="chapter" data-level="3.8.1" data-path="diagnostics.html"><a href="diagnostics.html#solutions-to-issues"><i class="fa fa-check"></i><b>3.8.1</b> Solutions to Issues</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3.9</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="3.9.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#indicator-variables"><i class="fa fa-check"></i><b>3.9.1</b> Indicator Variables</a></li>
<li class="chapter" data-level="3.9.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#interaction-variables"><i class="fa fa-check"></i><b>3.9.2</b> Interaction Variables</a></li>
<li class="chapter" data-level="3.9.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#causation"><i class="fa fa-check"></i><b>3.9.3</b> Causation</a></li>
<li class="chapter" data-level="3.9.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#conditions-for-multiple-linear-regression"><i class="fa fa-check"></i><b>3.9.4</b> Conditions for Multiple Linear Regression</a></li>
<li class="chapter" data-level="3.9.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#is-the-difference-real"><i class="fa fa-check"></i><b>3.9.5</b> Is the Difference Real?</a></li>
<li class="chapter" data-level="3.9.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#dealing-with-non-linear-relationships"><i class="fa fa-check"></i><b>3.9.6</b> Dealing with Non-Linear Relationships</a></li>
<li class="chapter" data-level="3.9.7" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#alternative-solutions"><i class="fa fa-check"></i><b>3.9.7</b> Alternative Solutions</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>3.10</b> Logistic Regression</a><ul>
<li class="chapter" data-level="3.10.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-and-logit"><i class="fa fa-check"></i><b>3.10.1</b> Logistic and Logit</a></li>
<li class="chapter" data-level="3.10.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-the-model"><i class="fa fa-check"></i><b>3.10.2</b> Fitting the Model</a></li>
<li class="chapter" data-level="3.10.3" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-1"><i class="fa fa-check"></i><b>3.10.3</b> Interpretation</a></li>
<li class="chapter" data-level="3.10.4" data-path="logistic-regression.html"><a href="logistic-regression.html#prediction-1"><i class="fa fa-check"></i><b>3.10.4</b> Prediction</a></li>
<li class="chapter" data-level="3.10.5" data-path="logistic-regression.html"><a href="logistic-regression.html#model-evaluation"><i class="fa fa-check"></i><b>3.10.5</b> Model Evaluation</a></li>
<li class="chapter" data-level="3.10.6" data-path="logistic-regression.html"><a href="logistic-regression.html#alternative-classification-models"><i class="fa fa-check"></i><b>3.10.6</b> Alternative Classification Models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="random-variability.html"><a href="random-variability.html"><i class="fa fa-check"></i><b>4</b> Random Variability</a><ul>
<li class="chapter" data-level="4.1" data-path="random-sampling-from-a-population.html"><a href="random-sampling-from-a-population.html"><i class="fa fa-check"></i><b>4.1</b> Random Sampling from a Population</a><ul>
<li class="chapter" data-level="4.1.1" data-path="random-sampling-from-a-population.html"><a href="random-sampling-from-a-population.html#irl-bootstrapping"><i class="fa fa-check"></i><b>4.1.1</b> IRL: Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="randomization-into-groups.html"><a href="randomization-into-groups.html"><i class="fa fa-check"></i><b>4.2</b> Randomization into Groups</a><ul>
<li class="chapter" data-level="4.2.1" data-path="randomization-into-groups.html"><a href="randomization-into-groups.html#irl-randomization-tests"><i class="fa fa-check"></i><b>4.2.1</b> IRL: Randomization Tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html"><i class="fa fa-check"></i><b>5</b> Randomness and Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="three-types-of-probability.html"><a href="three-types-of-probability.html"><i class="fa fa-check"></i><b>5.1</b> Three Types of Probability</a></li>
<li class="chapter" data-level="5.2" data-path="probability-rules.html"><a href="probability-rules.html"><i class="fa fa-check"></i><b>5.2</b> Probability Rules</a><ul>
<li class="chapter" data-level="5.2.1" data-path="probability-rules.html"><a href="probability-rules.html#diagnotic-testing-and-probability"><i class="fa fa-check"></i><b>5.2.1</b> Diagnotic Testing and Probability</a></li>
<li class="chapter" data-level="5.2.2" data-path="probability-rules.html"><a href="probability-rules.html#court-arguments-and-probability"><i class="fa fa-check"></i><b>5.2.2</b> Court Arguments and Probability</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variable.html"><a href="random-variable.html"><i class="fa fa-check"></i><b>5.3</b> Random Variable</a></li>
<li class="chapter" data-level="5.4" data-path="probability-models.html"><a href="probability-models.html"><i class="fa fa-check"></i><b>5.4</b> Probability Models</a><ul>
<li class="chapter" data-level="5.4.1" data-path="probability-models.html"><a href="probability-models.html#using-probability-mass-functions"><i class="fa fa-check"></i><b>5.4.1</b> Using probability mass functions</a></li>
<li class="chapter" data-level="5.4.2" data-path="probability-models.html"><a href="probability-models.html#using-probability-density-functions"><i class="fa fa-check"></i><b>5.4.2</b> Using probability density functions</a></li>
<li class="chapter" data-level="5.4.3" data-path="probability-models.html"><a href="probability-models.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.4.3</b> Expected value and variance</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="bernoullibinomial-model.html"><a href="bernoullibinomial-model.html"><i class="fa fa-check"></i><b>5.5</b> Bernoulli/Binomial Model</a></li>
<li class="chapter" data-level="5.6" data-path="normal-model.html"><a href="normal-model.html"><i class="fa fa-check"></i><b>5.6</b> Normal Model</a></li>
<li class="chapter" data-level="5.7" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html"><i class="fa fa-check"></i><b>5.7</b> Sampling Distribution and CLT</a><ul>
<li class="chapter" data-level="5.7.1" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html#sampling-distributions"><i class="fa fa-check"></i><b>5.7.1</b> Sampling distributions</a></li>
<li class="chapter" data-level="5.7.2" data-path="sampling-distribution-and-clt.html"><a href="sampling-distribution-and-clt.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.7.2</b> The Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html"><i class="fa fa-check"></i><b>5.8</b> Z-scores and the Student’s “t” distribution</a><ul>
<li class="chapter" data-level="5.8.1" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#gossets-work"><i class="fa fa-check"></i><b>5.8.1</b> Gosset’s Work</a></li>
<li class="chapter" data-level="5.8.2" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#beer-helps-the-field-of-statistics"><i class="fa fa-check"></i><b>5.8.2</b> Beer Helps the Field of Statistics</a></li>
<li class="chapter" data-level="5.8.3" data-path="z-scores-and-the-students-t-distribution.html"><a href="z-scores-and-the-students-t-distribution.html#student-t-model"><i class="fa fa-check"></i><b>5.8.3</b> Student T Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>6</b> Statistical Inference</a><ul>
<li class="chapter" data-level="6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>6.1</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="6.1.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#via-classical-theory"><i class="fa fa-check"></i><b>6.1.1</b> Via Classical Theory</a></li>
<li class="chapter" data-level="6.1.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#via-bootstrapping"><i class="fa fa-check"></i><b>6.1.2</b> Via Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html"><i class="fa fa-check"></i><b>6.2</b> Confidence Interval Examples</a><ul>
<li class="chapter" data-level="6.2.1" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#proportion-outcome"><i class="fa fa-check"></i><b>6.2.1</b> Proportion Outcome</a></li>
<li class="chapter" data-level="6.2.2" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#mean-and-then-median"><i class="fa fa-check"></i><b>6.2.2</b> Mean and then Median</a></li>
<li class="chapter" data-level="6.2.3" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#logistic-regression-model"><i class="fa fa-check"></i><b>6.2.3</b> Logistic Regression Model</a></li>
<li class="chapter" data-level="6.2.4" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#linear-regression-model-slope-categorical-variable"><i class="fa fa-check"></i><b>6.2.4</b> Linear Regression Model Slope (Categorical Variable)</a></li>
<li class="chapter" data-level="6.2.5" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#linear-regression-model-slope-quantitative-var"><i class="fa fa-check"></i><b>6.2.5</b> Linear Regression Model Slope (Quantitative Var)</a></li>
<li class="chapter" data-level="6.2.6" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#confidence-intervals-for-prediction"><i class="fa fa-check"></i><b>6.2.6</b> Confidence Intervals for Prediction</a></li>
<li class="chapter" data-level="6.2.7" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#prediction-intervals"><i class="fa fa-check"></i><b>6.2.7</b> Prediction Intervals</a></li>
<li class="chapter" data-level="6.2.8" data-path="confidence-interval-examples.html"><a href="confidence-interval-examples.html#probability-theory-vs.bootstrapping"><i class="fa fa-check"></i><b>6.2.8</b> Probability Theory vs. Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>6.3</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>6.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>6.3.2</b> Logic of hypothesis testing</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-of-procedure"><i class="fa fa-check"></i><b>6.3.3</b> Summary of procedure</a></li>
<li class="chapter" data-level="6.3.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#testing-single-model-coefficients"><i class="fa fa-check"></i><b>6.3.4</b> Testing single model coefficients</a></li>
<li class="chapter" data-level="6.3.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#distributions-of-test-statistics"><i class="fa fa-check"></i><b>6.3.5</b> Distributions of test statistics</a></li>
<li class="chapter" data-level="6.3.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#graphical-description-of-p-values"><i class="fa fa-check"></i><b>6.3.6</b> Graphical description of p-values</a></li>
<li class="chapter" data-level="6.3.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#example-linear-regression"><i class="fa fa-check"></i><b>6.3.7</b> Example: Linear Regression</a></li>
<li class="chapter" data-level="6.3.8" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#example-logistic-regression"><i class="fa fa-check"></i><b>6.3.8</b> Example: Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="statistical-significance-v-practical-significance.html"><a href="statistical-significance-v-practical-significance.html"><i class="fa fa-check"></i><b>6.4</b> Statistical Significance v. Practical Significance</a></li>
<li class="chapter" data-level="6.5" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>6.5</b> Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="appendix-a-theoretical-probability.html"><a href="appendix-a-theoretical-probability.html"><i class="fa fa-check"></i><b>7</b> Appendix A - Theoretical Probability</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stat 155 Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-linear-regression" class="section level2">
<h2><span class="header-section-number">3.9</span> Multiple Linear Regression</h2>
<p>We can generalize the idea of a simple linear model by including many explanatory variables (X’s). A <strong>multiple linear regression model</strong> can be written as:</p>
<p><span class="math display">\[\hat{y}_i = b_0 + b_1x_{i1} + \cdots + b_kx_{ik}\]</span></p>
<ul>
<li><p>Each coefficient <span class="math inline">\(b_j\)</span> can be interpreted as the increase in the predicted/average y associated with a 1 unit increase in <span class="math inline">\(x_j\)</span>, <strong>keeping all other variables constant</strong>. (*There are some exceptions - we’ll get there.)</p></li>
<li>These X variables can be:
<ul>
<li>Quantitative variables (or transformations of them)</li>
<li>Indicator variables for categorical variables (only need <span class="math inline">\(k-1\)</span> indicators for a variable with <span class="math inline">\(k\)</span> categories)</li>
<li>Interaction terms (product of two variables, which allows for <em>effect modification</em>)</li>
</ul></li>
</ul>
<p>Let’s talk about a new data example: home prices. We want to build a model to predict the price of a home based on its many characteristics. Here we have a data set of homes recently sold in New England with many variables such as the age of the home, the land value, whether or not it has central air conditioning, the number of fireplaces, the sale price, and more…</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" data-line-number="1">homes &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">&#39;http://sites.williams.edu/rdeveaux/files/2014/09/Saratoga.txt&#39;</span>)</a>
<a class="sourceLine" id="cb149-2" data-line-number="2"><span class="kw">head</span>(homes)</a></code></pre></div>
<pre><code>##    Price Lot.Size Waterfront Age Land.Value New.Construct Central.Air
## 1 132500     0.09          0  42      50000             0           0
## 2 181115     0.92          0   0      22300             0           0
## 3 109000     0.19          0 133       7300             0           0
## 4 155000     0.41          0  13      18700             0           0
## 5  86060     0.11          0   0      15000             1           1
## 6 120000     0.68          0  31      14000             0           0
##   Fuel.Type Heat.Type Sewer.Type Living.Area Pct.College Bedrooms
## 1         3         4          2         906          35        2
## 2         2         3          2        1953          51        3
## 3         2         3          3        1944          51        4
## 4         2         2          2        1944          51        3
## 5         2         2          3         840          51        2
## 6         2         2          2        1152          22        4
##   Fireplaces Bathrooms Rooms
## 1          1       1.0     5
## 2          0       2.5     6
## 3          1       1.0     8
## 4          1       1.5     5
## 5          0       1.0     3
## 6          1       1.0     8</code></pre>
<p>*The exception to the interpretation comment above is if our variables are strongly correlated. In this case, we cannot keep all other variables constant because if you increase the value of one, then a variable with high correlation will also likely change in value.</p>
<div id="indicator-variables" class="section level3">
<h3><span class="header-section-number">3.9.1</span> Indicator Variables</h3>
<p>In New England, fireplaces are often used as a way to heat the house. Let’s study the impact of a fireplace has on the sale price of a home. In particular, we only care if the home has 1 or more fireplaces or no fireplaces. So we make a new variable that is TRUE if there are more than 0 fireplaces in a home and FALSE otherwise.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" data-line-number="1">homes &lt;-<span class="st"> </span>homes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb151-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">AnyFireplace =</span> Fireplaces <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</a></code></pre></div>
<p>In order to include this information in our linear regression model, we need to turn that categorical variable (<code>AnyFireplace</code>, TRUE or FALSE) into an <strong>indicator variable</strong>, which has a numeric value of 0 or 1:</p>
<p><span class="math display">\[ 1_{AnyFireplaceTRUE} = \begin{cases}1 \quad \text{ if a home has at least one fireplace}\\ 0\quad \text{ if a home does not have a fireplace} \end{cases}\]</span></p>
<p>In fact, R creates this indicator for you when you put a categorical variable as an X variable in the model.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" data-line-number="1">lm.home &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>AnyFireplace, <span class="dt">data =</span> homes)</a>
<a class="sourceLine" id="cb152-2" data-line-number="2"><span class="kw">tidy</span>(lm.home)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term             estimate std.error statistic  p.value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)       174653.     3419.      51.1 0.      
## 2 AnyFireplaceTRUE   65261.     4522.      14.4 1.17e-44</code></pre>
<p>Our “best fitting line” is</p>
<p><span class="math display">\[ \hbox{Predicted Price} = 174653.35 + 65260.61 \times 1_{AnyFireplaceTRUE} \]</span></p>
<p><strong>What does this mean?</strong></p>
<p>Let’s think about two types of homes: a home with one or more fireplaces and a home without a fireplace. Let’s write out the equations for those two types of homes.</p>
<ul>
<li>Home with fireplace:<br />
<span class="math display">\[ \hbox{Predicted Price} = 174653.35 + 65260.61 \times 1 = \$ 239,914 \]</span></li>
</ul>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" data-line-number="1"><span class="fl">174653.35</span> <span class="op">+</span><span class="st"> </span><span class="fl">65260.61</span><span class="op">*</span><span class="dv">1</span></a></code></pre></div>
<pre><code>## [1] 239914</code></pre>
<ul>
<li>Home without fireplace:<br />
<span class="math display">\[ \hbox{Predicted Price} = 174653.35 + 65260.61 \times 0 = \$ 174,653.35 \]</span></li>
</ul>
<p>The difference between these predicted prices is $65,260.61. So is this how much a fireplace is worth? If I installed a fireplace in my house, should the value of my house go up $65,260?</p>
<ul>
<li>No, because we are not making causal statements based on observational data. What could be confounding this relationship? What third variable may be related to both the price and whether or not a house has a fireplace?</li>
</ul>
<p>Let’s look at the size of the house. Is price related to the area of living space (square footage)?</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" data-line-number="1">homes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb156-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Living.Area, <span class="dt">y =</span> Price)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">color =</span> <span class="st">&#39;steelblue&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb156-4" data-line-number="4"><span class="st">    </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Is the presence of a fireplace related to area of living space?</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" data-line-number="1">homes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb157-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> AnyFireplace, <span class="dt">y =</span> Living.Area)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb157-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb157-4" data-line-number="4"><span class="st">    </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>We see that the amount of living area differs between homes with fireplaces and homes without fireplaces. Thus, Living Area could confound the relationship between AnyFireplace and Price because it is related to both variables.</p>
<p>Let’s put Living Area in the model along with AnyFireplace to account for it (to control/adjust for it).</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" data-line-number="1">lm.home2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>AnyFireplace <span class="op">+</span><span class="st"> </span>Living.Area, <span class="dt">data =</span> homes)</a>
<a class="sourceLine" id="cb158-2" data-line-number="2"><span class="kw">tidy</span>(lm.home2)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term             estimate std.error statistic   p.value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)        13599.   4992.        2.72 6.51e-  3
## 2 AnyFireplaceTRUE    5567.   3717.        1.50 1.34e-  1
## 3 Living.Area          111.      2.97     37.5  2.20e-225</code></pre>
<p>Our “best fitting line” is</p>
<p><span class="math display">\[ \hbox{Predicted Price} = 13599.16 + 5567.37 \times 1_{AnyFireplaceTRUE} + 111.21 \times \hbox{Living.Area} \]</span></p>
<p><strong>What does this mean?</strong></p>
<p>Let’s think about two types of homes: a home with one or more fireplaces and a home without a fireplace.</p>
<ul>
<li>Home with fireplace:<br />
<span class="math display">\[
\begin{align*}
\hbox{Predicted Price} &amp;= 13599.16 + 5567.37 \times 1 + 111.21 \times \hbox{Living.Area} \\
&amp;= \$19,166.53 + \$111.21 \times \hbox{Living.Area}
\end{align*}
\]</span></li>
</ul>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" data-line-number="1"><span class="fl">13599.16</span> <span class="op">+</span><span class="st"> </span><span class="fl">5567.37</span><span class="op">*</span><span class="dv">1</span></a></code></pre></div>
<pre><code>## [1] 19166.53</code></pre>
<ul>
<li>Home without fireplace:<br />
<span class="math display">\[
\begin{align*}
\hbox{Predicted Price} &amp;= 13599.16 + 5567.37 \times 0 + 111.21 \times \hbox{Living.Area} \\
&amp;= \$13,599.16 + \$111.21 \times \hbox{Living.Area}
\end{align*}
\]</span></li>
</ul>
<p>If we keep Living.Area constant by considering two equally sized homes, then we’d expect the home with the fireplace to be worth $5567.37 more than a home without a fireplace. We see this by taking the difference between the two equations:</p>
<p><span class="math display">\[ \hbox{Predicted Price (with Fireplace)} - \hbox{Predicted Price (without Fireplace)} \]</span>
<span class="math display">\[
\begin{align*}
\,&amp;= (\$19,166.53 + \$111.21 \times \hbox{Living.Area}) - ( \$13599.16 + \$111.21 \times \hbox{Living.Area})
\,&amp;= \$19,166.53 - \$13,599.16 = \$5567.37
\end{align*}
\]</span></p>
<p>The difference between the intercepts is 5567.37.</p>
<ul>
<li><p>Note this was the estimated coefficient for AnyFireplaceTRUE.</p></li>
<li><p>So the $5567.37 is the increase in the predicted or average Price associated with a 1 unit change in AnyFireplace (TRUE or FALSE), <strong>keeping all other variables (Living.Area) constant</strong>.</p></li>
<li><p>Similarly, we could reason that $111.21 is the increase in the predicted or average Price associated with a 1 square footage increase in Living.Area, <strong>keeping all other variables (AnyFireplace) constant</strong>.</p></li>
</ul>
<p>Let’s look back at the relationship between Living.Area and Price and color the scatterplot by AnyFireplace. So we are now looking at three variables at a time. The above model with AnyFireplace and Living.Area results in two lines, with different intercepts but the same slope (parallel lines).</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" data-line-number="1">homes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb162-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Living.Area, <span class="dt">y =</span> Price, <span class="dt">color =</span> AnyFireplace)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb162-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb162-4" data-line-number="4"><span class="st">    </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-123-1.png" width="672" /></p>
<p>Let’s try and fit two separate lines to these two groups of homes, home with any fireplaces and home with no fireplaces. Do these lines have the same intercepts? Same slopes?</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" data-line-number="1">homes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb163-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Living.Area, <span class="dt">y =</span> Price, <span class="dt">color =</span> AnyFireplace)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb163-4" data-line-number="4"><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb163-5" data-line-number="5"><span class="st">    </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-124-1.png" width="672" /></p>
<p>In this case, it look as though having a fireplace in your house slightly changes the relationship between Living.Area and Price. In fact, having a fireplace in your house, the increase in your price for every 1 square foot is greater than that for homes without fireplaces (slopes are different).</p>
</div>
<div id="interaction-variables" class="section level3">
<h3><span class="header-section-number">3.9.2</span> Interaction Variables</h3>
<p>We can actually allow for different slopes within one regression model, rather than fitting two separate models.</p>
<ul>
<li><p>If we add a variable in the model as is, it changes the intercept.</p></li>
<li>We can achieve different slopes by allowing a variable <span class="math inline">\(x_1\)</span> to affect the slope for another variable <span class="math inline">\(x_2\)</span>. That is, <span class="math inline">\(x_1\)</span> impacts the effect of <span class="math inline">\(x_2\)</span> on the outcome <span class="math inline">\(y\)</span>. (Fireplace presence impacts the effect of living area on house price.)
<span class="math display">\[b_2 = a + bx_1\]</span>
This is called <strong>effect modification</strong> (when one variable can modify the effect of another variable on the outcome).</li>
<li><p>A model with effect modification looks like:
<span class="math display">\[\hat{y} = b_0 + b_1x_{1} + b_2x_{2}= b_0 + b_1x_{1} + (a+bx_1)x_{2}= b_0 + b_1x_{1} +ax_2+bx_1x_{2}\]</span>
The model above has an <strong>interaction term,</strong> which is the product of two variables. Here we have <span class="math inline">\(x_1*x_2\)</span>.</p></li>
</ul>
<p>Let’s build an effect modification model for our housing data. Let’s include an interaction term between AnyFireplace and Living.Area to allow for different slopes.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" data-line-number="1">lm.home3 &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>AnyFireplace<span class="op">*</span>Living.Area, <span class="dt">data =</span> homes)</a>
<a class="sourceLine" id="cb164-2" data-line-number="2"><span class="kw">tidy</span>(lm.home3)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   term                         estimate std.error statistic  p.value
##   &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)                   40901.    8235.        4.97 7.47e- 7
## 2 AnyFireplaceTRUE             -37610.   11025.       -3.41 6.61e- 4
## 3 Living.Area                      92.4      5.41     17.1  1.84e-60
## 4 AnyFireplaceTRUE:Living.Area     26.9      6.46      4.16 3.38e- 5</code></pre>
<p><strong>What does this mean?</strong></p>
<p>Let’s think about two types of homes: a home with one or more fireplaces and a home without a fireplace.</p>
<ul>
<li>Home with fireplace:<br />
<span class="math display">\[
{\small
\begin{align*}
\hbox{Predicted Price} &amp;= 40901.29 + -37610.41 \times 1 + 92.36391 \times \hbox{Living.Area} + 26.85 \times \hbox{Living.Area} \times 1 \\
&amp; = \$3,290.88 + \$119.21 \times \hbox{Living.Area}
\end{align*}
}
\]</span></li>
</ul>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1"><span class="fl">40901.29</span> <span class="op">+</span><span class="st"> </span><span class="fl">-37610.41</span><span class="op">*</span><span class="dv">1</span></a></code></pre></div>
<pre><code>## [1] 3290.88</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1"><span class="fl">92.36391</span> <span class="op">+</span><span class="st"> </span><span class="fl">26.85</span><span class="op">*</span><span class="dv">1</span></a></code></pre></div>
<pre><code>## [1] 119.2139</code></pre>
<ul>
<li>Home without fireplace:<br />
<span class="math display">\[
{\small
\begin{align*}
\hbox{Predicted Price} &amp;= 40901.29 + -37610.41 \times 0 + 92.36391 \times \hbox{Living.Area} + 26.85 \times \hbox{Living.Area} \times 0 \\
&amp;= \$40,901.29 + \$92.36 \times \hbox{Living.Area}
\end{align*}
}
\]</span></li>
</ul>
<p>We see a different slope and different intercepts for these two groups.</p>
</div>
<div id="causation" class="section level3">
<h3><span class="header-section-number">3.9.3</span> Causation</h3>
<p>We alluded earlier that multiple linear regression could provide estimates of causal effects in the right circumstances. What are those circumstances? When we include <strong>all</strong> confounding variables. This entails being specific about what a confounding variable is. A confounder is a <strong>common cause</strong> of both the causal variable of interest and the outcome. (e.g. Living area could be a confounder of fireplace presence and house price.)</p>
<p>We also alluded earlier that we should not just throw every variable we have into a multiple regression model. Why? Imagine a scenario for understanding how smoking affects lung cancer development. It is very important to consider whether a variable is a <strong>mediator</strong> of the relationship between the cause and the outcome. A mediator in this example could be tar. Suppose that smoking only affects lung cancer risk by creating tar on the lungs. If we adjust for tar (by holding it constant), then we also effectively hold smoking constant too! If smoking is held constant, then we cannot estimate its effect on cancer risk because it is not varying!</p>
<p>Wait - we could never possibly know of or measure all confounding variables, could we!? This is true, but that doesn’t mean that our endeavor to understand causation is fruitless. As long as we can describe the relationship between known confounders as precisely as possible, we have a starting ground for moving forward. We collect data, analyze how well our model predicts that data, and collect more data based on that, perhaps measuring more potential confounders as our scientific knowledge grows. We can also conduct sensitivity analyses by asking: how strongly must a confounder affect the variable of causal interest and the outcome to completely negate or reverse the association we see? Such endeavors and more are the subject of the field of <em>causal inference</em>.</p>
<p><em>Reminder: If you want a “gentle” but mathematical introduction to Causal Inference, I’d suggest reading “Causal Inference in Statistics: A Primer” by Judea Pearl, Madelyn Glymour, Nicholas P. Jewell). Fun Fact: Nicholas Jewell was Prof. Heggeseth’s PhD advisor!</em></p>
</div>
<div id="conditions-for-multiple-linear-regression" class="section level3">
<h3><span class="header-section-number">3.9.4</span> Conditions for Multiple Linear Regression</h3>
<p>In order for a multiple linear regression model to make sense,</p>
<ul>
<li>Relationships between each quantitative <span class="math inline">\(X\)</span>’s and <span class="math inline">\(Y\)</span> are <strong>straight enough</strong> (check scatterplots and residual plot)</li>
<li>About <strong>equal spread</strong> of residuals across fitted values (check residual plot)</li>
<li>No extreme outliers (points far away in X’s can have <strong>leverage</strong> to change the line)</li>
</ul>
</div>
<div id="is-the-difference-real" class="section level3">
<h3><span class="header-section-number">3.9.5</span> Is the Difference Real?</h3>
<p>We could ask: is there <em>really</em> a difference in the slopes for Living Area and Price between homes with and without a fireplace?</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1">lm.home4 &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Living.Area<span class="op">*</span>AnyFireplace, <span class="dt">data =</span> homes) </a>
<a class="sourceLine" id="cb170-2" data-line-number="2"><span class="kw">summary</span>(lm.home4)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Living.Area * AnyFireplace, data = homes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -241710  -39588   -7821   28480  542055 
## 
## Coefficients:
##                                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   40901.294   8234.665   4.967 7.47e-07 ***
## Living.Area                      92.364      5.412  17.066  &lt; 2e-16 ***
## AnyFireplaceTRUE             -37610.413  11024.853  -3.411 0.000661 ***
## Living.Area:AnyFireplaceTRUE     26.852      6.459   4.157 3.38e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 68760 on 1724 degrees of freedom
## Multiple R-squared:  0.513,  Adjusted R-squared:  0.5122 
## F-statistic: 605.4 on 3 and 1724 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>If we ask ourselves this question, we are assuming a few things:</p>
<ol style="list-style-type: decimal">
<li><p>We would like to make a general statement about a <strong>target population of interest</strong>.</p></li>
<li><p>We don’t have data for everyone in our population (we don’t have a <strong>census</strong>).</p></li>
<li><p>Depending on who ends up in our <strong>sample</strong>, the relationship/difference/estimate may change a bit.</p></li>
<li><p>We want to know how much the relationship/difference/estimate may change based on <strong>sampling variation.</strong></p></li>
</ol>
<ul>
<li>Let’s treat our sample (of size <span class="math inline">\(n\)</span>) as our ‘fake’ population (since we don’t have the full population).
<ul>
<li>Randomly sample from our sample (with replacement) a new sample of size <span class="math inline">\(n\)</span></li>
</ul></li>
<li>Calculate the least squares regression line.</li>
<li>Repeat.</li>
</ul>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">333</span>) <span class="co">## Setting the seed ensures that our results are reproducible</span></a>
<a class="sourceLine" id="cb172-2" data-line-number="2"><span class="co">## Repeat the sampling and regression modeling 1000 times</span></a>
<a class="sourceLine" id="cb172-3" data-line-number="3">boot &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">1000</span>)<span class="op">*</span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Living.Area<span class="op">*</span>AnyFireplace, <span class="dt">data =</span> <span class="kw">resample</span>(homes))</a>
<a class="sourceLine" id="cb172-4" data-line-number="4"></a>
<a class="sourceLine" id="cb172-5" data-line-number="5"><span class="co">## Plot the distribution of the 1000 slope differences</span></a>
<a class="sourceLine" id="cb172-6" data-line-number="6">boot <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb172-7" data-line-number="7"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Living.Area.AnyFireplaceTRUE)) <span class="op">+</span></a>
<a class="sourceLine" id="cb172-8" data-line-number="8"><span class="st">    </span><span class="kw">geom_histogram</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb172-9" data-line-number="9"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Bootstrap Difference in Slopes&#39;</span>)</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p>This is called <strong>Bootstrapping</strong> and it is used to:</p>
<ol style="list-style-type: decimal">
<li>Measure the variability in the estimate (the estimate is the difference in slopes in this case) between random samples and</li>
<li>Provide an interval of plausible values for the estimate (the estimate is the difference in slopes in this case).</li>
</ol>
<p>Let’s first look at the variability of the difference in slopes across the bootstrap samples. The standard deviation of the slopes will be similar to the std.error from the linear model output.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" data-line-number="1">boot <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb173-2" data-line-number="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">sd</span>(Living.Area.AnyFireplaceTRUE))<span class="co">#this is going to be of similar magnitude to the Std Error in output</span></a></code></pre></div>
<pre><code>##   sd(Living.Area.AnyFireplaceTRUE)
## 1                         9.332937</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" data-line-number="1"><span class="kw">tidy</span>(lm.home4)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   term                         estimate std.error statistic  p.value
##   &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)                   40901.    8235.        4.97 7.47e- 7
## 2 Living.Area                      92.4      5.41     17.1  1.84e-60
## 3 AnyFireplaceTRUE             -37610.   11025.       -3.41 6.61e- 4
## 4 Living.Area:AnyFireplaceTRUE     26.9      6.46      4.16 3.38e- 5</code></pre>
<p>This standard deviation is somewhat close to the <span class="math inline">\(6.459\)</span> in the Std. Error column of the <code>summary(lm.home4)</code> output above.</p>
<p>To get an interval of plausible values, we look at the histogram and take the middle 95%. The lower end will be the 2.5th percentile and the upper end will be the 97.5th percentile.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" data-line-number="1">boot <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb177-2" data-line-number="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(Living.Area.AnyFireplaceTRUE, <span class="fl">0.025</span>), <span class="dt">upper =</span> <span class="kw">quantile</span>(Living.Area.AnyFireplaceTRUE, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##      lower    upper
## 1 7.686552 45.43513</code></pre>
<div class="reflect">
<p>
Based on this evidence, do you think it is possible that the slopes are the same for the two types of homes (with and without fireplaces)?
</p>
</div>
</div>
<div id="dealing-with-non-linear-relationships" class="section level3">
<h3><span class="header-section-number">3.9.6</span> Dealing with Non-Linear Relationships</h3>
<p>If we notice a curved relationship between two quantitative variables, it doesn’t make sense to use a straight line to approximate the relationship.</p>
<p>What can we do?</p>
<div id="transform-variables" class="section level4">
<h4><span class="header-section-number">3.9.6.1</span> Transform Variables</h4>
<p>One solution to non-linear relationships is to transform the explanatory (X) variables or transform the outcome variable (Y).</p>
<p><strong>Guideline #1:</strong> If there is unequal spread around the curved relationship, focus first on transforming Y. If the spread is roughly the same around the curved relationship, focus on transforming X.</p>
<p>When we say transform a variable, we are referring to taking the values of a variable and plugging them into a mathematical function such as <span class="math inline">\(\sqrt{x}\)</span>, <span class="math inline">\(\log(x)\)</span> (which represents natural log, not log base 10), <span class="math inline">\(x^2\)</span>, <span class="math inline">\(1/x\)</span>, etc.</p>
<p><strong>Guideline #2:</strong> We will focus on power functions and organize them in a <strong>Ladder of Powers</strong> of y (or x):</p>
<p><span class="math display">\[
\begin{align}
\vdots\\
y^3\\
y^2\\
\mathbf{y = y^1}\\
\sqrt{y}\\
y^{1/3}\\
y^{0} ~~~  (we~use~\log(y)~here )\\
y^{-1/3}\\
1/\sqrt{y}\\
1/y\\
1/y^2\\
\vdots
\end{align}
\]</span></p>
<p>We start at <span class="math inline">\(y\)</span> (power = 1) and think about going up or down the ladder.</p>
<p>But which way?</p>
<p>Our friend J.W. Tukey (the same guy who invented the boxplot) came up with an approach to help us decide. You must ask yourself: Which part of the circle does the scatterplot most resemble (concavity and direction)? Which quadrant?</p>
<p><strong>Guideline #3:</strong> The sign of x and y in the quadrant tells you the direction to move on the ladder (positive = up, negative = down).</p>
<p><img src="Photos/tukey.png" width="400" height="500" /></p>
<p>Practice: Which quadrant does this relationship below resemble?</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" data-line-number="1"><span class="kw">require</span>(gapminder)</a>
<a class="sourceLine" id="cb179-2" data-line-number="2"></a>
<a class="sourceLine" id="cb179-3" data-line-number="3">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-4" data-line-number="4"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb179-5" data-line-number="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp, <span class="dt">x =</span>  gdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-132-1.png" width="672" /></p>
<p>Based on this plot, we see that the spread is roughly equal around the curved relationship and that it is concave down and positive (quadrant 2: top left). This suggests that we focus on going down the ladder with x.</p>
<p>Try these transformations until you find a relationship that is roughly straight. If you go too far, the relationship will become more curved.</p>
<p>Let’s try going down the ladder.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" data-line-number="1">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb180-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb180-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> <span class="kw">sqrt</span>(gdpPercap)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb180-4" data-line-number="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp, <span class="dt">x =</span>  TgdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb180-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p>Not quite straight. Let’s keep going.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" data-line-number="1">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb181-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb181-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> gdpPercap<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb181-4" data-line-number="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp, <span class="dt">x =</span>  TgdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb181-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<p>Not quite straight. Let’s keep going.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb182-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb182-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> <span class="kw">log</span>(gdpPercap)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb182-4" data-line-number="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp, <span class="dt">x =</span>  TgdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb182-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<p>Getting better. Let’s try to keep going.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" data-line-number="1">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb183-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb183-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> <span class="dv">-1</span><span class="op">/</span>gdpPercap) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb183-4" data-line-number="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp, <span class="dt">x =</span>  TgdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb183-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-136-1.png" width="672" /></p>
<p>TOO FAR! Back up. Let’s stick with log(gdpPercap).</p>
<p>Now we see some unequal spread so let’s also try transforming Y.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" data-line-number="1">gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb184-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb184-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> <span class="kw">log</span>(gdpPercap)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb184-4" data-line-number="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TlifeExp =</span> lifeExp<span class="op">^</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb184-5" data-line-number="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> TlifeExp, <span class="dt">x =</span>  TgdpPercap)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb184-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
<p>That doesn’t change it much. Maybe this is as good as we are going to get.</p>
<p>Transformations can’t make relationships look exactly linear with equal spread, but sometimes we can make it closer to that ideal.</p>
<p>Let’s try and fit a model with just these two variables.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" data-line-number="1">lm.gap &lt;-<span class="st"> </span>gapminder <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2005</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb185-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TgdpPercap =</span> <span class="kw">log</span>(gdpPercap)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-4" data-line-number="4"><span class="st">  </span><span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span>TgdpPercap, <span class="dt">data =</span> .)</a>
<a class="sourceLine" id="cb185-5" data-line-number="5"></a>
<a class="sourceLine" id="cb185-6" data-line-number="6"><span class="kw">summary</span>(lm.gap)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ TgdpPercap, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.947  -2.661   1.215   4.469  13.115 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.9496     3.8577   1.283    0.202    
## TgdpPercap    7.2028     0.4423  16.283   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.122 on 140 degrees of freedom
## Multiple R-squared:  0.6544, Adjusted R-squared:  0.652 
## F-statistic: 265.2 on 1 and 140 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretations</strong></p>
<p>What does <span class="math inline">\(b_1\)</span> mean in this context?</p>
<p><span class="math display">\[\widehat{LifeExp} = b_0 + b_1 log(Income)\]</span></p>
<ul>
<li><p>The slope is the the additive increase in <span class="math inline">\(\widehat{LifeExp}\)</span> when <span class="math inline">\(log(Income)\)</span> increases to <span class="math inline">\(log(Income) + 1\)</span>.</p></li>
<li><p>Let’s think about <span class="math inline">\(log(Income) + 1\)</span>. Using some rules of logarithms:</p></li>
</ul>
<p><span class="math display">\[log(Income) + 1 = log(Income) + log(e^1) = log(e*Income) = log(2.71*Income)\]</span>
So adding 1 to <span class="math inline">\(log(Income)\)</span> is equivalent to multiplying Income by 2.71.</p>
<p>In our model, we note that if GDP is increased by 271% (multiplying by 2.71) the predicted average life expectancy of a country increases by about 7.2 years.</p>
<p>For the sake of illustration, imagine we fit a model where we had transformed life expectancy. What does <span class="math inline">\(b_1\)</span> mean in this context?</p>
<p><span class="math display">\[\widehat{log(LifeExp)} = b_0 + b_1 Income\]</span></p>
<ul>
<li><p>The slope is the the additive increase in <span class="math inline">\(\widehat{log(LifeExp)}\)</span> when <span class="math inline">\(Income\)</span> increases to <span class="math inline">\(Income + 1\)</span>.</p></li>
<li><p>Let’s think about <span class="math inline">\(\widehat{log(LifeExp)} + b_1\)</span>. Using rules of logarithms:
<span class="math display">\[\widehat{log(LifeExp)} + b_1 = \widehat{log(LifeExp)} + log(e^{b_1}) = log(\widehat{LifeExp} * e^{b_1}) \]</span>
The additive increase in <span class="math inline">\(log(LifeExp)\)</span> is a multiplicative increase of <span class="math inline">\(LifeExp\)</span> by a factor of <span class="math inline">\(e^{b_1}\)</span>.</p></li>
</ul>
</div>
</div>
<div id="alternative-solutions" class="section level3">
<h3><span class="header-section-number">3.9.7</span> Alternative Solutions</h3>
<p>We could also model non-linear relationships by including higher degree terms in a linear model like the example below. By using poly(), we now include <span class="math inline">\(x\)</span> and <span class="math inline">\(x^2\)</span> as variables in the model.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb187-2" data-line-number="2">y &lt;-<span class="st"> </span><span class="dv">200</span> <span class="op">+</span><span class="st"> </span><span class="dv">20</span><span class="op">*</span>x <span class="op">-</span><span class="st"> </span><span class="dv">5</span><span class="op">*</span>x<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>,<span class="dt">sd =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb187-3" data-line-number="3">dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,y)</a>
<a class="sourceLine" id="cb187-4" data-line-number="4">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-5" data-line-number="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb187-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb187-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" data-line-number="1"><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, <span class="dt">degree =</span> <span class="dv">2</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>), <span class="dt">data =</span> dat)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ poly(x, degree = 2, raw = TRUE), data = dat)
## 
## Coefficients:
##                      (Intercept)  poly(x, degree = 2, raw = TRUE)1  
##                          192.806                            23.305  
## poly(x, degree = 2, raw = TRUE)2  
##                           -5.379</code></pre>
<p>A more advanced solution (which is not going to be covered in class) is a generalized additive model, which allows you to specify which variables have non-linear relationships with y and estimates that relationship for you using spline functions (super cool stuff!). We won’t talk about how this model is fit or how to interpret the output, but there are other cool solutions out there!</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" data-line-number="1"><span class="kw">require</span>(gam)</a>
<a class="sourceLine" id="cb190-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">gam</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">s</span>(x), <span class="dt">data =</span> dat))</a></code></pre></div>
<pre><code>## Warning in model.matrix.default(mt, mf, contrasts): non-list contrasts
## argument ignored</code></pre>
<p><img src="Stat155Notes_files/figure-html/unnamed-chunk-140-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="diagnostics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Stat155Notes.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
